### ISSUE TITLE
Surge compatibility list (macOS,Windows,Linux)

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#105]
This one is really rather complex.

From my end, I'm able to confirm that:

## macOS 64-bit AudioUnit (macOS Mojave)
- [X] Logic Pro X
- [X] Ableton Live 10

## macOS 64-bit VST2 (macOS Mojave)
- [X] Renoise 64bit V3.1.1

@asimilon posted these:

> Live10 : VST2 works, AU won't load at all (VST3 not supported).
> Reaper : VST3 works, AU loads in some weird bridge mode and I don't get sound, VST2 doesn't show up at all.
> Cubase 9.5 : VST2 works, VST3 won't load at all (AU not supported).
> Cubase 8.5 : VST3 loads but doesn't produce sound, no sign of VST2.
> Logic Pro X 10.4.1 : AU works (VST of course not supported)

Anyone else wanna pitch in? @abique @jsakkine @whydoubt @kmatheussen @kzantow

**Comment by jsakkine** [comment]
Apologies for asking meta-questions, but since these are tickets how do we get this closed?

**Comment by jsakkine** [comment]
@esaruoho: what I would propose is to add a section to `README.md`. That would be really useful. You get the initial list from what you have here. We can then update it when we get something working.

**Comment by jsakkine** [comment]
But maybe just a coarse matrix with platform and target to keep it nice, compact and easy to look at.

**Comment by baconpaul** [comment]
Yeah @esaruoho maybe you can make docs/COMPATABILITY.md then point people at that from the README. We can update it when we get improvements. Good idea!
