### ISSUE TITLE
Surge-AU: 4 enumeration values not handled in switch: 'cg_GLOBAL', 'cg_MIX', 'cg_FILTER'... (Add missing switch cases)

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#109]
So, I'm trying to run Surge-AU via Xcode and am getting this error:

`4 enumeration values not handled in switch: 'cg_GLOBAL', 'cg_MIX', 'cg_FILTER'...`

in `SurgeGUIEditor.cpp`.

What might I be doing wrong, @baconpaul ?

**Comment by baconpaul** [comment]
That's just a warning no?

I fixed it on one of my branches.

**Comment by esaruoho** [comment]
> That's just a warning no?
> I fixed it on one of my branches.

well that's weird - it doesn't seem to be fixed in kurasu/surge:master -- can it be?

**Comment by esaruoho** [comment]
closing.. something wrong with my repo
