### ISSUE TITLE
Surge-VST2: files in public.sdk/source/vst2.x not found

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#110]
Hi, I've got the export set ( `export VST2SDK_DIR="~/work/VST2.4SDK"` ) yet when I go to build `surge-vst2` with xcode, I get these:

`'public.sdk/source/vst2.x/aeffeditor.h' file not found (aeffguieditor.h)`
`'public.sdk/source/vst2.x/audioeffectx.h' file not found (Vst2PluginInstance.h)`
`'public.sdk/source/vst2.x/aeffeditor.h' file not found (aeffguieditor.h)`

should these be found?

**Comment by baconpaul** [comment]
Seems you are seeing a lot of breaks. Are you sure your branch is at head and your build is clean? I just did a build fro! Master and it all worked

**Comment by baconpaul** [comment]
Oh but I don't have vst2; so ignore that!

**Comment by esaruoho** [comment]
i speak about this in greater detail in #113  - will post some of the segments from this issue in there and close this one.
