### ISSUE TITLE
Unable to build installer on Windows VM

### ISSUE THREAD

**Issue by kzantow** [kurasu/surge#126]
Trying to get Windows builds working per #97 but I'm having issues getting the project built. `msbuild` reports:
```
D:\a\1\s\surge-vst3.vcxproj(341,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\libpng-msvc-x64.1.6.33.8807\build\native\libpng-msvc-x64.targets
```
And the same error for VST2. I've tried adding an explicit NuGet step and using the `restoreNugetPackages` option, but nothing really seems to solve this issue -- I don't really have a handy Windows machine at the moment, so any pointers what I'm doing wrong or how to solve it would be greatly appreciated.

@baconpaul not sure if you're familiar with Windows builds but if so, would love you to chime in.

**Comment by baconpaul** [comment]
@kzantow I haven't done anything with windows in a very long time, so have nothing to offer here, sorry!

**Comment by kzantow** [comment]
Okay, I figured this out, apparently it's just necessary to run `NuGet` separately. Now, does anyone know how to automate install of `Inno Setup` on a VM?

**Comment by asimilon** [comment]
> how to automate install of `Inno Setup` on a VM

I assume looking at that `D:\a\1\s\surge...` path above this is on Azure Pipelines?

In which case Chocolately is available on the Windows VMs, and InnoSetup is [an available package](https://chocolatey.org/packages/InnoSetup).

**Comment by kzantow** [comment]
@esaruoho no; however if someone could provide any Visual Studio commands I can run to build Win 32, I'll be happy to add them to the build script(s). For now, closing this as it was related to a `NuGet` issue
