### ISSUE TITLE
Any chance of MIT-style license?

### ISSUE THREAD

**Issue by getdunne** [kurasu/surge#15]
Use of GPL3 means no one can ever use any of this code in a closed-source application. Does Steinberg's new "dual license" permit no alternative? This code could be more widely usable if at least some of it -- at least the parts which don't depend on the VST SDK -- could be governed by a less-restrictive license such as MIT or BSD.

**Comment by Moth-Tolias** [comment]
> Use of GPL3 means no one can ever use any of this code in a closed-source application.

this is the point of the GPL3.

**Comment by getdunne** [comment]
> this is the point of the GPL3.

I know that. I would prefer a less restrictive, non-viral license, and I was asking if the author would (or could) consider it.

**Comment by asimilon** [comment]
Nothing about VST license stopping it (afaik), but why would he want to allow someone else to profit from his hard work?  Because surely the only reason for it to be "more widely used" would be in a closed source codebase whose binaries are being sold.

**Comment by getdunne** [comment]
Use of GPL3 means even a small piece of the code can't be used in any non-GPL project. This includes open-source libraries licensed under MIT, BSD, etc. If this is what the author wants, so be it, but it's his decision. @kurasu what do you say?

**Comment by esaruoho** [comment]
@kurasu since you own the repo and are the originator of the plugin code, what do you think of this request from @getdunne ?i mean, maybe if it has been decided that it won't change, maybe this ticket can be closed.. or something?

**Comment by jsakkine** [comment]
- GPL3 governs from someone making a closed version of Surge with improvements that are not given back to the community.
- Implementing this issue would require all the copyright holders (i.e. everyone who has contributed to the codebase) to mutually agree with the license change.

@baconpaul, can you close this issue? I think with these conclusions we can consider it implemented.

**Comment by jsakkine** [comment]
@esaruoho: doesn't matter from copyright law perspective who owns to repository. They should have some kind of contributor agreement in place like some projects have in order to get implicit copyright transfer. Since there isn't one this project has as many copyright holders as there are contributors.

**Comment by baconpaul** [comment]
It would be lovely to have a contribution agreement. Are there any standard open ones folks use for smaller GPL3 projects? @jsakkine if you know of one want to open another issue? I agree we should close this one.

And the original copyright holder chose GPL3 and the rest of us contributed knowing that, so I agree, it’s unlikely to change.

**Comment by jsakkine** [comment]
Not really expert on contribution agreements and to initiate it you would have to get everyone to agree who has contributed so far to have one. You **can** have that or change the license by creating an issue and asking everyone (including @kurasu) to "sign" it. Agreeing with the license change is probably easier than getting everyone to give away their copyright to the changes that they have written. At this point of time at least the license change would still be doable.

I don't see the current GPL3 really a problem. And things like algorithmic ideas are not protected by any open source license anyway so this project does not really impair one from doing commercial plugin development in the future. That is but evil corporations use patents for :)

**Comment by jsakkine** [comment]
For example, Linux has multiple copyright holders, not a single entity.

**Comment by baconpaul** [comment]
I was wondering if there was a cc-sa-4.0 style contribution agreement but then you we need an entity or an individual who will hold the copyright and to administer the execution of it and so on. I don't think it's going to happen.

So GPL3 merged copyright is probably how we will stay. I'm fine working that way on this project!
