### ISSUE TITLE
Update Surge-plugin About screen?

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#157]
mainly talking about the image below..
<img width="898" alt="surge_50-surge" src="https://user-images.githubusercontent.com/4966687/50454143-3b63b500-094e-11e9-9bac-1de932de4d06.png">

says 2005-2015, Vember Audio, and Version is 1.6.0.. where are these texts coming from?
I tried doing git greps but was unable to come up with anything.

**Comment by whydoubt** [comment]
https://github.com/kurasu/surge/blob/master/resources/bitmaps/bmp00158.png

**Comment by baconpaul** [comment]
Yeah this is just an image blatted on.

In an ideal world, our build pipeline would create some file which had some defined strings we could paint on the screen. But it doesn't yet. @jsakkine is it possible cmake could construct "versions.h" or some such at build time so we could do this?

**Comment by kurasu** [comment]
I'm not so sure either but we definitely need something automatic that we just render at runtime. 

I think we at least want

- Version or revision & branch
- The contributors
- Link to here
- Copyright notices as required by the VST2, 3 and Audio Units SDKs

Not sure if copyright is relevant, but the GPL license might be.

**Comment by jsakkine** [comment]
Does SVG exist for the Surge logo?

**Comment by kurasu** [comment]
No, it's a 3D render, but I should have a higher res version somewhere.. But it could also be time for a new logo, it's been >10 years.

**Comment by baconpaul** [comment]
So the reason people appear twice - or at least I do - is that my GitHub id has proper name "paul" and my mac git global configuration has my full name.  If you use "%aN %ae" you can see the fact that at least for me the "paul" is baconpaul@users.noreply.github.com and Rich and Richie are the same email address.

I agree with @kurasu list of what should go in the screen. I would also include a build time and build date.

**Comment by jsakkine** [comment]
I could write easily a Python script using GitPython that grabs the authors list and filters out broken names. Seems like the best option really. Once it is done, it is done.

**Comment by esaruoho** [comment]
yeah, auto-generated "all that's been discussed in the comments above" feels like the right way to go.

incidentally, there's a TON of lines in the code to the tone of

```
Copyright 2005 Claes Johanson & Vember Audio
```

or

```
Copyright 2006 Claes Johanson & Vember Audio
```

or

```
Copyright 2005-2006 Claes Johanson & Vember Audio
```

or

```
Copyright 2004 Claes Johanson
```

or even

```
Copyright 2005 Claes Johanson & vember|audio
```

-- what should these actually say? I could take a hand and fix them all, but I don't know what they should say.

**Comment by esaruoho** [comment]
@jsakkine cool, seems like a good step forwards!

**Comment by jsakkine** [comment]
I go with the Python script. It adds a build dep but otherwise is the only non-flakky solution.

**Comment by baconpaul** [comment]
We probably don't want to change those copyright lines, @esaruoho - that copyright still applies to that bit of code. With GPL3 and no contributor agreement (which is how we are working) each contributor maintains copyright to their changes, basically, and the GPL3 makes it open. I would be hesitant to remove any copyright information from the code.

**Comment by jsakkine** [comment]
Ok, the next problem: what the generated header would look like? What kind of data structures wants the GUI code consume?

**Comment by baconpaul** [comment]
How about you just make a reasonable xml file and drop it in resources directory at end of build process - then we can try and load it and do whatever we want. Resources/build-info.xml or some such?

**Comment by jsakkine** [comment]
JSON or XML. Either WFM. Does XML have any particular benefits over JSON?

**Comment by jsakkine** [comment]
Revamping the about dialog raises an interesting question. What would be a good multi-platform way to present text and translations? There must be some best practice for that? Completely out of my territory.

**Comment by baconpaul** [comment]
> JSON or XML. Either WFM. Does XML have any particular benefits over JSON?
 
Pragmatically we already have an xml parser integrated with the codebase whereas we don’t have a Json parser. So less code expansion if we go xml.

**Comment by baconpaul** [comment]
> What would be a good multi-platform way to present text and translations

Well there’s well defined apis on all platforms. They do a variety of things but here’s a reasonable mental model. Basically you make a strings file which contains mapping from ids to display strings, write one for each language, put it in resources, call a platform specific way to pick one, and then use it. Then walk your code and bitmaps to replace string literals and pre rendered strings with the id lookup or a draw. It’s a well understood path but it is a pain to retrofit.

**Comment by baconpaul** [comment]
Sure for some subset. But we also need bitmaps in each language and so need a way to inclement that. And if you read closely you will see that there’s still some implementation details on how to find the string files. That class is an encapsulation of some of the things I had mentioned when you asked how to do it though.

**Comment by jsakkine** [comment]
... or you can use the same bitmaps and just translate text? I'm fine of not doing any type of translations for 1.6.

**Comment by baconpaul** [comment]
The text is in the bitmaps. So words like “about” are not painted with a font in c code so we could use an indirection to a string, but instead are painted by drawing a bitmap which contains pixels which spell about. So we either need to change that in the drawing code everywhere or do one set of bitmaps per language

And yeah I agree this isn’t a 16 thing!

**Comment by jsakkine** [comment]
@baconpaul, Ugh, that I didn't know. Makes it fairly obvious not to include...

**Comment by baconpaul** [comment]
I’ll take a crack at this over the weekend but just doing a little pre thinking and wanted to remember this https://stackoverflow.com/questions/9240188/how-to-load-a-custom-binary-resource-in-a-vc-static-library-as-part-of-a-dll for when I turn to it

**Comment by baconpaul** [comment]
OK starting to plumb this together. 

This diff https://github.com/baconpaul/surge/commit/7f47a746693ab4096abb9174c67150cf7f2815ce removes the pre-painted text and instead paints text which is at least coded. It also includes a date and time of build on the about screen. It refers people to GitHub for contributors and information.

<img width="891" alt="screen shot 2019-01-03 at 7 31 42 pm" src="https://user-images.githubusercontent.com/13387561/50668632-375b1700-0f8e-11e9-900e-6a929b3cd24d.png">

here's what it looks like.

So the extra step here is to create an XML file in a portable way (tough; can we assume python with the git module is everywhere? etc) and then on Mac put it in the resources directory after build and on windows put it in the premake and redo it with each build so that it is a compiled in resource. That's tricky.

I sort of want to get at least a date and time into the about screen though since if we start doing more regular builds can help with bugs.

So any thoughts on the above screen and diff? How would folks feel if I put that interim step in as a PR while someone wrangles with the build steps to create more information?

**Comment by esaruoho** [comment]
@baconpaul sounds good!

**Comment by baconpaul** [comment]
OK I'll put that first change in as a PR and leave it linger for a day or so to see if there are any comments.

**Comment by kurasu** [comment]
@baconpaul looks good!

**Comment by cyanit** [comment]
![aboutscreen](https://user-images.githubusercontent.com/26248671/50724306-98e4c800-10eb-11e9-9608-e5fbab2a77bf.png)

This is the current (exept for the logo) about screen in the 1.6 skin (afc only as long as everyone is happy about it). The temporary pink and green boxes are 20x20 pixels/20x10 pixels. Would it be possible it draw the version ino this way:
Font-Family: Lato
Font: Lato Regular
Size: 12pt
Space between Lines: 10 pixels

The first lines position would be X: 37/ Y: 442.
![position](https://user-images.githubusercontent.com/26248671/50724273-1bb95300-10eb-11e9-847c-80f0f9016338.PNG)

**Comment by baconpaul** [comment]
We actually render with a draw here so use font metrics for a system font. We want the about screen to have build information. So if you can just leave the text out we can adapt when we get a skin together

We do need the vst and au icons I think. Also a gpl and GitHub icon would be lovely

**Comment by cyanit** [comment]
yes, understood that the text is just there for a visual representation of what it could look like. Github and GPL cons are a nice idea. Will look into that.

**Comment by baconpaul** [comment]
Cool.
Is lato a free font? If so maybe we could load it from a resource in the bundle. If not we can’t resist of course

**Comment by cyanit** [comment]
yes, just head over to google fonts. Should be one if its there.

**Comment by baconpaul** [comment]
Ok great
No promises on being able to load a ttf but openframeworks can do it crossplatform so I bet we could coerce vstgui to do so also somehow

**Comment by jsakkine** [comment]
Question about Python script. I can generate XML but wouldn't make more sense to generate a header with data structures that contain what we want? Authors and version are both static data that is directly associated with the build where they are generated. I do not see why take the extra parsing step run-time.

**Comment by baconpaul** [comment]
I thought about that. Where are you going to put it so it won't get checked in, still builds, and works with premake on all platforms. Seemed more fiddly to me. Better to just blat an xml file into resources I thought.

But I'm easy! 

We sure python is configured on all our build hosts btw? I was worried about that a tiny bit.

**Comment by jsakkine** [comment]
Doesn't premake have some kind of environment variable for the build folder? Output `<build folder>/include` and add it to the include path. You can use `prebuildcommands` for invoking script and outputting the header.

Of top of my head, locating the Python interpreter is done with `PYTHONPATH` environment in all OSs. GitPython does not come with default installation and must be installed by issuing `pit install gitpython`.

**Comment by baconpaul** [comment]
Probably. Yeah.

I know you know this - but we want to generate the header at each build time, not at each premake time.

Also we need to make sure the header goes some place that is .gitignored.

Does windows ship with a python interpreter by default now? Are you going to run the pip install in the premake or test for it and ask the user to, like we do with sub modules? Also python 2 or python 3. And so on. I wish python were more reliably installed on rando users box. But all surmountable. Just remember to put in a bunch of defensive checks for things like python isn’t there; python 3 isn’t there; pip doesn’t run; that sort of thing.

**Comment by baconpaul** [comment]
Actually thinking: One reason to do an XML file into resources rather than a header.

If the python blah de blah isn’t installed  on a users machine and no XML file is created, I can fail to parse the XML gracefully at runtime and they still get a build. They don’t come here and open a github issue saying “how do I get python”.

If the python blah de blah isn’t installed in header land, though, `#include “build_info.h”` will puke.

So if you go python for header route we need to make sure that in the event python environment isn’t set up we copy some default build_info with all the fields defined to some state so the code still builds for that user.

Obviously we wouldn’t do a distribution build from that state. But it will save @esaruoho some pain in the Kvr forum one day I’m sure!

**Comment by jsakkine** [comment]
@baconpaul, if you don't mind ignore your other comment just focus the one on premake. Doesn't `prebuildcommands` come actually become part of the generated Makefile? What premake does is to build to build files.

**Comment by baconpaul** [comment]
Yeah it does! And ignoring me is often smart. I think the thing we really need to be careful of, though, is being super defensive about the python environment on the machine with clear error messages. Do that and get it working all three platforms and a header file is definitely the way to go.

**Comment by jsakkine** [comment]
@baconpaul, those were decent comments. Just not sure what to say to them at this point yet :)

**Comment by baconpaul** [comment]
Ha! Yeah I got that @jsakkine no worries here. Made me chuckle.

One solution I thought of out of this, though, was super simple. Write your python script assuming everything is in place. Then make a wrapper script (or two; one in sh one in cmd) which does

```
python blah
if ( exit code not 0 )
   copy precanned header file into place so it builds and has error values
```

then at least if the python fails the build continues and the about screen is wrong. Then we can disable the silent failure in azure builds later.

But I'm just tossing out ideas which pop into my head. Use them iff they are useful.

**Comment by jsakkine** [comment]
I think we should have these two files in the root of the project:

- `VERSION` file with one line containing the version string 
- `AUTHORS` file containing the authors in _FirstName LastName <Email>_ format.

I think `AUTHORS` **must** be maintained manually. The initial file can be generated from the commit log but already there we have inconsistencies that need to be manually resolved. Things like that might happen also in the future. Automation here probably is a bad idea in the end of the day.

As a side-effect this sorts out the _GitPython_ dependency.

**Comment by jsakkine** [comment]
With the version file premake5.lua could probably create `SURGE_VERSION` macro definition by using `io.readfile()`.

**Comment by esaruoho** [comment]
looking good at HEAD but i guess this could be tweaked further re: what @jsakkine wrote.
![vember_audio__surge__ 64bit__and_renoise__intel_64bit_](https://user-images.githubusercontent.com/4966687/50838637-30a21a80-1367-11e9-9398-bc1cae18c6f5.jpg)

or is this ticket ready to be closed? @baconpaul whatcha think?

**Comment by jsakkine** [comment]
For authors it can be easily seen that you cannot be done it reliably without a manual process. It is not just "take the correct fields from the commit log".

**Comment by jsakkine** [comment]
@esaruoho, that text comes from an image or? Could not grep it from the tree. Would be nice at least to tweak the version number from the VERSION-file.

**Comment by baconpaul** [comment]
If you are up to date with master as of about 3 days ago you will find that text in src/common/GUI/cabouttext

**Comment by baconpaul** [comment]
And let’s not close it yet

**Comment by jsakkine** [comment]
Found it. I'll do a patch to read the version to the about screen.

**Comment by jsakkine** [comment]
An awkward problem. I put this to the top of premake5.lua:

```
defines { "SURGE_VERSION=" .. io.readfile("VERSION") }
```
It does end up into the makefile:

```
$ premake5 --cc=gcc --os=linux gmake
Building configurations...
Running action 'gmake'...
Generated Makefile...
Generated surge-vst3.make...
Generated surge-app.make...
Done (83ms).

$ grep SURGE_VERSION *.make         
surge-app.make:  DEFINES += -DVSTGUI_ENABLE_DEPRECATED_METHODS=0 -DDEBUG=0 -DRELEASE=1 -DSURGE_VERSION=1.6.0
surge-vst3.make:  DEFINES += -DVSTGUI_ENABLE_DEPRECATED_METHODS=0 -DDEBUG=0 -DRELEASE=1 -DSURGE_VERSION=1.6.0
```

Still I get that `error: ‘SURGE_VERSION’ was not declared in this scope` when I try to use it in the source code.

**Comment by baconpaul** [comment]
No idea if this is it but don’t we normally do premake with the gmake2 argument?

**Comment by jsakkine** [comment]
@baconpaul, OK, was not aware of that. The result is still the same tho.

**Comment by baconpaul** [comment]
Can you run make in a verbose mode so you can inspect the command line? Seems related to your aligned free issue too which is defined in premake yeah?

**Comment by jsakkine** [comment]
Got this one. It was declared in a  place that it became part of the release-configuration i.e.

```
configuration { "Release*" }
defines { "DEBUG=0", "RELEASE=1" }
optimize "Speed"
targetdir "target/Release"

defines { "SURGE_VERSION=" .. io.readfile("VERSION") }

configuration {}
```

**Comment by jsakkine** [comment]
Probably not related to the other build issue.

**Comment by jsakkine** [comment]
Still sorting out this issue: https://github.com/premake/premake-core/issues/1216. You can do two-level macro dance to stringify any macro value easily but would be nice if premake5 could already output nicely formed definition.

**Comment by jsakkine** [comment]
OK, did a PR for pulling out the version string. At least way it is defined in premake5.lua is clean, and the way I stringify it by using cpp, is also a de-facto way to do stuff like this. `STR(x)` is a useful macro to have.

**Comment by jsakkine** [comment]
Seems like the solution I have in the PR is the "least bad" way to do it (the only compiler independent way). See the discussion in the premake issue.

**Comment by baconpaul** [comment]
I think what we have is good enough for 1.6 so lets close this. Thanks @jsakkine

**Comment by jsakkine** [comment]
Great, now I start to look more into Linux issues. I think in the GUI side there is enough helping hands. I think I bring the most value to this project with all this plumbing work.
