### ISSUE TITLE
Windows builds are b0rked

### ISSUE THREAD

**Issue by kzantow** [kurasu/surge#165]
Getting back to Azure Pipeline build scripts to build Mac and Windows, it looks like the Windows builds have been hosed. I'm trying to install a Windows VM and VC++ to diagnose/fix this...

The gist of the issue(s) are:
```
\src\common\dsp\quadfilterunit.cpp(947): error C2065: 'SINUS_SSE2': undeclared identifier [\surge-vst3.vcxproj]
\src\common\vt_dsp\vt_dsp_endian.h(22): error C3861: '__builtin_bswap32': identifier not found (compiling source file src\common\dsp\Wavetable.cpp) [\surge-vst3.vcxproj]
```

**Comment by baconpaul** [comment]
Wonder if it is pr #151?

**Comment by baconpaul** [comment]
Or maybe #138

**Comment by baconpaul** [comment]
Yeah those two are the only pr to be in that part of the code that I see.

**Comment by kzantow** [comment]
@baconpaul yeah, I think #138 ... will report back once I have a windows dev environment

**Comment by kzantow** [comment]
@baconpaul confirmed `623a12adef62e447479510ae75b68f0cbd306501~1` does not have the same issue and builds successfully on Azure; I think it's a generally good change, removing PPC support, that is, will see if I can quickly get it building

**Comment by baconpaul** [comment]
Ok darn it. I’m sorry.

@jsakkine seems like the ppc cleanup broke windows. @kzantow if you find the fix I can merge it. Up for a bit still.

**Comment by baconpaul** [comment]
Quadfilterunit in-line 1255 pre and 729 post the wrong endif was removed knocking out sse symbol you see

**Comment by kzantow** [comment]
FYI - [free trial Windows development environment... only 20 GB!](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines)

**Comment by baconpaul** [comment]
Oh that is super useful. I will grab that in the morning

**Comment by jsakkine** [comment]
Sorry about this. Setting up Windows environment.

**Comment by kzantow** [comment]
@jsakkine no worries, seems to be sorted out now
