### ISSUE TITLE
polish: installer: GNU General Public License <- weird tabbing/spaces going on

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#168]
when viewing the macOS installer, it does some weird sort of dump of the GNU GPL textfile, which is split into all kinds of small pieces, and the "titles" are kinda buggily handled too. this could probably be tweaked easily, right?

![install_install_surge_2018-12-27_and_cleanmymac_and_itunes](https://user-images.githubusercontent.com/4966687/50472732-b070d200-09c2-11e9-9d7f-81a7a1c3df26.jpg)

**Comment by baconpaul** [comment]
Just so you know, there's a relatively easy but tedious fix for this.

The installer in installer_osx includes Resources/License.txt which is a copy of the GPL3 which exactly matches LICENSE in the top. This file has newlines every 70 characters or so so it reads well when you cat and less it.

The installer UI shows the license and wraps it narrower. That means words like "designed" gets pushed onto a new line.

So the solutions include doing things like editing Resources/License.txt and making each paragraph a single long line so the macOS wraps it. Or write a clever little script to do that once. Or so on.

**Comment by esaruoho** [comment]
I would tend to think that making single long lines is the way to go. i could try and do it, in fact.

**Comment by esaruoho** [comment]
@baconpaul here's a PR for it. #194

**Comment by baconpaul** [comment]
Thanks!
