### ISSUE TITLE
Remove stricmp=strcasecmp definition from premake5.lua

### ISSUE THREAD

**Issue by jsakkine** [kurasu/surge#173]
There are not many call sites:

```
$ ngit grep stricmp  
premake5.lua:		"stricmp=strcasecmp",
premake5.lua:		"stricmp=strcasecmp",
src/common/Sample.cpp:   if (!stricmp(extension, "wav"))
src/common/dsp/DspUtilities.h:   if (_stricmp(str, "yes") == 0)
src/common/gui/CSurgeSlider.cpp:   if (!stricmp(txt, "filter balance"))
src/vst2/vstplugsquartz.h:#define stricmp strcmp
```
i.e. four call sites in total.

Probably makes the code more readable if you know, which symbol gets actually called.

**Comment by baconpaul** [comment]
I especially like that it is strcasecmp except in the vst2, where it isn't!

**Comment by whydoubt** [comment]
While this shouldn't be a part of the definitions in premake.lua, I don't like needing an #if/#else/#endif each time this is needed.  I think taking care of it in once in a common header would be better.

**Comment by baconpaul** [comment]
Oh those platform ifs are added? Sheesh I had read that backwards

Yes I agree.

**Comment by baconpaul** [comment]
And actually thinking about it: why is this a bad thing for premake or cmake to define on Mac and Linux? We don’t have a common header across the whole project.
