### ISSUE TITLE
visually correct ASSYM as ASYM

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#182]
this is Asymmetric Waveshaper, not Assymmetric, right?

<img width="324" alt="screenshot_29_12_2018__12_56" src="https://user-images.githubusercontent.com/4966687/50537504-1ac37700-0b69-11e9-9b71-12818233dac6.png">

**Comment by baconpaul** [comment]
Just FYI thats in the bitmap not the code so we need to render from assets or use mspaint to fix or some such

**Comment by baconpaul** [comment]
@itsmedavep can you transcribe this one over to your new skin bug issue also, reference it, and then I’ll close it here as a dupe

**Comment by esaruoho** [comment]
well okay closing
