### ISSUE TITLE
Suggestion: fix sorting of patches in submenus to be A->Z?

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#183]
the patch loading submenus are not A-to-Z, instead whatever goes wherever. Surely something like that could be fixed, or what do you think @inigokennedy ?

<img width="456" alt="fullscreen_29_12_2018__12_56" src="https://user-images.githubusercontent.com/4966687/50537516-3cbcf980-0b69-11e9-8f7f-0efa7842c870.png">

**Comment by baconpaul** [comment]
They are just in whatever order readdir returns. A sort is a good idea and easy enough.

**Comment by baconpaul** [comment]
@jsakkine you were looking for a way to get into the ui. This one is pretty easy. There’s a vector ctge assembled in CPatchBrowser.cpp in the onmousedown. Apply the right flavor of std::sort to it before the subgroup iteration and this should be fixed.

**Comment by baconpaul** [comment]
Or I can do it in the new year. But just thought this may be an easier approach to Mac dev and test than the other harder one with parameter invalidation

**Comment by baconpaul** [comment]
Also looking at that screenshot we may want to adjust the split to submenu threshold

**Comment by baconpaul** [comment]
Oh and don’t forget to remap indices. Alternately you could sort the entire structure when it is loaded in surgestorage. That way you can sort categories too. But then you need to adjust when you save one as a user. Not sure which I would do - would want to stare at code a minute more

**Comment by jsakkine** [comment]
@baconpaul, what is split to submenu threshold?

**Comment by jsakkine** [comment]
I think `SurgeStorage` is the appropriate choice, and instead of sorting, I'd just put categories to `std::map`.

**Comment by jsakkine** [comment]
Actually, `std::set` should do as `struct patchlist_category` contains only a `std::string` member.

**Comment by jsakkine** [comment]
Ugh, did not understand how deep in the code category array indexes are use as global identifiers, so yeah, doing something simpler while still trying to also clean up thinks just a bit.

**Comment by jsakkine** [comment]
Commits done. No, PR yet because I only know that they compile at this point. If you want to take risk, go ahead and try (and give feedback).

**Comment by jsakkine** [comment]
PR done. Next time I will do something to this will after NYE.

**Comment by jsakkine** [comment]
Thanks for linking that! Just starting work on this.

**Comment by esaruoho** [comment]
fingers crossed!

**Comment by jsakkine** [comment]
@baconpaul, just detailing a bit #183 to check that I've not missed something.

To the class SurgeStorage we add:

```
std::vector<int> categoryOrdering;
std::vector<int> patchOrdering;
```

I think these are more descriptive names than `patch_traversal_map`.

These must be generated in the tail of `SurgeStorage::refresh_patchlist()` . Is it too intrusive to rename this function as `refreshPatchList()`?

For categories the correct index is mapped here in `CPatchBrowser::onMouseDown()`:

```
   for (int c = 0; c < storage->patch_category.size(); c++)
   {
      int c2 = storage->categoryOrdering[c];
```

For patches the index is mapped in this sub-loop of the former:

```
         for (int p = 0; p < storage->patch_list.size(); p++)
         {
            int p2 = storage->patchOrdering[p];
            if (storage->patch_list[p2].category == c)
            {
               ctge.push_back(p2);
            }
         }
```

I though to check the design before sending PRs.

**Comment by baconpaul** [comment]
Your name is better than patch_traversal_map tho

I would not rename refresh_patchlist at this point, since it will make the textual diff bigger than the semantic diff

I would probably not use p and p2; rather I’d use names like “patchIndex” and “patchSortedIndex”

Also it’s weird to iterate over patch list size and then get from patch ordering. Why wouldn’’t

```
for (int p = 0; p < storage->patch_list.size(); p++)
         {
            int p2 = storage->patchOrdering[p];
```

Just be

```
  For ( auto p : storage->patchOrdering )
```

Instead?

But looks like the right path!

**Comment by jsakkine** [comment]
OK, cool.

Then what about splitting a category into multiple submenus? I remember that from earlier review.

**Comment by baconpaul** [comment]
There’s code there that does that already. I just think the constant is set wrong. But yeah two steps is fine.

**Comment by jsakkine** [comment]
Is this how it should look like (*sort-patch-list* branch in my GIT):

![image](https://user-images.githubusercontent.com/112336/50736320-ec771480-11c4-11e9-8ea0-2fbadfe63aa7.png)

**Comment by jsakkine** [comment]
I've chosen to prefix everything with `std::` because generally it is considered an anti-pattern to import a whole namespace in a header file (e.g. `globals.h`).  And using makes actually the code more readable than not using it (short prefix and functions like `std::iota()` would look cryptic without that prefix).

**Comment by baconpaul** [comment]
That looks great!

Wonder if you should apply the same to wavetables while you are in there?

And yeah I use std:: everywhere and also looked sideways a little at the use namespace std in globals.h. Fine with me.

**Comment by baconpaul** [comment]
Oh and you are case insensitive sorting right? Polysynth has all sorts of case conventions on the patches.

**Comment by jsakkine** [comment]
I can show my lambda for patches:

```
   auto patchCompare =
      [this](const int &i1, const int &i2) -> bool
      {
         return _stricmp(patch_list[i1].name.c_str(),
                         patch_list[i2].name.c_str()) < 0;
      };
```

**Comment by jsakkine** [comment]
Tried that now without my commit applied (i.e. master branch) with the latest changes from mainline. I saved a patch named as *Jarkko's Test* with category *Pad*. 

The result is that I can see the patch in a Pad category in user patches group but I cannot see it in factory patches group in that category. Are you sure that this should work?

**Comment by baconpaul** [comment]
I just tried with my master and yes I see Pad in both places.

Xcode cleans "poorly". Generally when I switch branches I do a ./build-osx.sh --clean-all. Maybe you had a remnant of your branch in your build assets? But it is definitely the case that user patch categories matching factory patch categories show up twice.

<img width="523" alt="screen shot 2019-01-06 at 8 41 43 am" src="https://user-images.githubusercontent.com/13387561/50736722-e6664100-118e-11e9-8494-ab03a69658bf.png">

**Comment by baconpaul** [comment]
Without looking at your code, maybe what's happening is since you sort on name, two categories with the same name are ambiguous. Perhaps patch_category needs an id which gets incremented when created and you check if that's distinct. 

And your patch sort lambda - does that need to compare categories before names? Or do you apply that sort on a per-category basis?

Again just thinking out loud.

**Comment by jsakkine** [comment]
OK, I might gotten this wrong what you said earlier. I see the Pad category twice exactly as in your screenshot with and without my commit. But I cannot find *Jarkko's Test* in both 
*Pad*-menus.

**Comment by baconpaul** [comment]
Oh that’s right. It will only appear in user
If you take a factory preset and store it without changing name same category same name should appear twice

If you rename it the new one only appears once

**Comment by jsakkine** [comment]
OK, then it works as expected and my commit does not break anything :) I'll do the WT-part and send a PR.

**Comment by jsakkine** [comment]
Proof:

![image](https://user-images.githubusercontent.com/112336/50736964-7676ab80-11cc-11e9-97f6-7b300949e53c.png)

**Comment by jsakkine** [comment]
And this:

![image](https://user-images.githubusercontent.com/112336/50737107-429c8580-11ce-11e9-9ec8-f24fd4df69a8.png)

I'll prepare a PR now.

**Comment by baconpaul** [comment]
Yay great! I’m out and about today but I will look at the pr in detail either tonight nyc time or tomorrow morning. Thank you

**Comment by esaruoho** [comment]
@jsakkine yeah just hook me up with how i get the code from your repo.

**Comment by jsakkine** [comment]
@esaruoho, I guess you ack this now?

**Comment by esaruoho** [comment]
I tried it and on the surface everything looks fine. I have not saved a patch tho cos feel like that is a way huger thing to bugshoot

**Comment by baconpaul** [comment]
Thanks @jsakkine - all great stuff! I just merged it. Closing this issue.
