### ISSUE TITLE
uppercase wavetables refuse to load / display "AKALSAX.WT" "KALT1.WT"

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#191]
kvr-birdies told me that `AKALSAX.WT` and `KALT1.WT` do not load.

[akalsax_wt_and_kalt1_wt.zip](https://github.com/kurasu/surge/files/2720048/akalsax_wt_and_kalt1_wt.zip)

see below for accurate commentary

**Comment by esaruoho** [comment]
i added these files (and made copies and renamed them to lowercase .wt
and saw the added folder display, but its contents were not read. i.e. mouse over on VST2/Live == no files show.

<img width="511" alt="fullscreen_02_01_2019__9_04" src="https://user-images.githubusercontent.com/4966687/50582754-75ace500-0e6d-11e9-9bed-a80089c7aa47.png">

**Comment by esaruoho** [comment]
Modified the name of the ticket.
The issue doesn't seem to be that user-generated content `cannot` be loaded, the issue is that if a file has uppercase `.WT` it is not shown.

details:

`akalsax_lowercasewt.wt` = displays
`AKALSAX_uppercasewt.WT` = does not display
`AKALSAX_capitalWt.Wt` = does not display

surely something like this could be easily fixed, wdyt @baconpaul @jsakkine

**Comment by esaruoho** [comment]
macOS: VST2: Renoise 3.1.1
<img width="685" alt="fullscreen_02_01_2019__9_09" src="https://user-images.githubusercontent.com/4966687/50582839-231ff880-0e6e-11e9-866c-a154a1de1a5f.png">

macOS: AU: Logic Pro X
<img width="559" alt="fullscreen_02_01_2019__9_10" src="https://user-images.githubusercontent.com/4966687/50582875-65493a00-0e6e-11e9-90e5-9ca96c40225b.png">

macOS: AU: Live 10
<img width="456" alt="fullscreen_02_01_2019__9_11" src="https://user-images.githubusercontent.com/4966687/50582886-7abe6400-0e6e-11e9-826a-6dd70377b57e.png">

macOS: VST2: Live 10
<img width="464" alt="fullscreen_02_01_2019__9_13" src="https://user-images.githubusercontent.com/4966687/50582922-b1947a00-0e6e-11e9-84b8-4623b8bee7d9.png">

**Comment by baconpaul** [comment]
Just pushed  a fix to this. Probably more coming in the next few days so I would wait before telling user to rebuild but your option.
