### ISSUE TITLE
Some thoughtwork required for "where to put presets/user-saved patches"

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#192]
Hi, at least on macOS, according to some on kvr-audio, we're in this unenviable situation where patches are saved to

~/Library/Application Support/Surge
OR
~/Documents/Surge
OR
/Library/Application Support/Surge

could we make our minds up as to how this should be done? Doesn't it make sense to have all the patches in one specific place? or..?
Any thoughts would be valid, right about now.
@kurasu @abique @jsakkine @kmatheussen @baconpaul @kzantow @asimilon @whydoubt @idoleat

**Comment by baconpaul** [comment]
Let’s pick a few other synths and see what they do. Like what does the Arturia collection do or some such? Then add that to this issue so we can decide 

User patches can’t go in /library

**Comment by idoleat** [comment]
I know some DAWs can automatically gather all patches into one place for each plugin, like FL, and I enjoy that feature. However some don't. It would be nice to have all patches in one place so I can easily pick the same patch while switching between DAWs. Just pick from that specific directory and done.

**Comment by baconpaul** [comment]
OK here's what surge does today

1: The factory patches are loaded from /Library/Application Support/Surge or ~/Library/Application Support/Surge depending on how you have it set up
2: If you make and save a patch in a new category that category becomes a subdir in ~/Documents/Surge
3: *this is the somewhat screwy bit* If you load a factory patch (like "Sequences / I want to get well") and them modify it and save it it goes in ~/Documents/Surge. Then when you look at the patch list you have the "Sequence" subcategory both in the top factory section and in the lower user section.

I don't think that is crazy behavior but it's not precisely expected. 

You can compare it with what the Arturia collection does (which has a lot of great presets and is super patchable). If you load a factory patch and modify it, you don't have a "store" option, you only have a "save as" option. Once you "save as" it into a custom "bank" (which is basically like a subdirectory for patches) it shows up in the dropdown menu and you can save it again and again. I don't know where the files actually go to be honest, but it has an export feature where you can package up patches.

So perhaps the solution here is

1: User patches go into ~/Documents
2: User patches can't have category names which conflict with factory or third party category names
3: There's good error reporting and UI on that (so like if you save a factory patch the category comes up as blank)

Then if we want to add new factory patches we just do it in the filesystem I guess?

I dunno. What do people think?

(oh and I guess there will be a similar problem with user generated waveforms one day too but lets use a separate ticket for that!)

**Comment by cyanit** [comment]
Usually, a DAW looks for "content" in certain places. For VST2, this is a bit difficult, but VST3 has clearly defined places where the VST (C:\Program Files (x86)\Common Files\VST3) and its data need to go. In the case of Bitwig Studio, all you need to do is add the VST3 preset directory (C:\Users\USER\Documents\VST3 Presets) to your content directories (if it isn't already added by default) and you're good to go.

In VST2, the patch storage is up to the plugin manufacturer/dev. U-He and NI store stuff in other directories, they even let you define where, which is great, I store all my content on a separate HDD. 
I have a directory called plugin data (C:\VST Plugin Data) where I usually direct my VSTs to when they ask for "data storage", (Grace, PG-8X, U-He plugins, and Glitch 2 use this, just to name a few). 

Personally, I'm against cluttering the documents folder (and letting the user decide where he wants his data to be), but as it seems all programmes do it today cause it's a simple solution.

Heres what others do:
**Application Folder** C:\Program Files\KV331 Audio\SynthMaster\Presets
**Documents** C:\Users\Leo\Documents\Native Instruments\Massive\Sounds
**Custom** C:\VST Plugin Data\U-He\Hive.data\Presets\Hive

**Comment by jsakkine** [comment]
Serum installer creates Serum folder under Documents and creates subfolders for presets, wavetables etc. there. Then it just copies there all the factory content.  It also pre-creates `Serum/Presets/User Presets` for user presets.

I like the simplicity of Serum's approach. Easy to move stuff to different machines etc.

**Comment by esaruoho** [comment]
for me, `~/Documents/Surge` is perfect since I use iCloud Drive == means that any computer I use automatically has my patches available to me. 

I would tend to close this issue, WDYT @baconpaul @jsakkine ?

**Comment by baconpaul** [comment]
Fine with me. I don’t see anything not working
