### ISSUE TITLE
Kvraudio: Bitwig: sceneB automation parameters issue

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#193]
From aMUSEd on kvraudio:
There is something odd going on with host automation assignments for Scene B. If I try and 'learn' params from the filters in scene B in Bitwig for example (in order to create a device panel map), by clicking learn then selecting the filter cutoff, res etc, what gets learnt is LFO params, not filter params. The only way to map filter params (or any params from Scene B) is via the drop-down selector but that is an endless list and very disorganised.

**Comment by baconpaul** [comment]
Platform and unit type?

**Comment by esaruoho** [comment]
@baconpaul i asked on kvr and he said `MacOs Sierra, VST2, Bitwig 2.4`

**Comment by esaruoho** [comment]
another mention
```
the automation parameters for the B part seem to be bugged. they're all mis-assigned. for example f1 cutoff registers as LFO2 Delay.
```
(from 
https://www.kvraudio.com/forum/viewtopic.php?p=7181915#p7181915 )

**Comment by baconpaul** [comment]
I can test vst3 bitwig no problem. I don’t have ability to build vst2

**Comment by esaruoho** [comment]
@baconpaul grab the kzantow build of vst2?-)

**Comment by esaruoho** [comment]
@baconpaul yeah im trying to stress that ”post bugs to kvr with lazy instructions and complaints” is. NOT. the way to go. I am yet to see them ”get it”.

**Comment by baconpaul** [comment]
Ha I just took a swing by the kvr audio forum. You are doing thankless work it seems, but let me thank you for trying!

**Comment by baconpaul** [comment]
Closing as dup with 247
