### ISSUE TITLE
Surge: Audio Input?

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#196]
Does anyone know how to use the Surge AudioInput, and what it does?

<img width="432" alt="fullscreen_03_01_2019__22_48" src="https://user-images.githubusercontent.com/4966687/50660818-c75a8a00-0fa9-11e9-9d09-d89f9543618f.png">

**Comment by esaruoho** [comment]
okay, so far i've identified that the audio input sound is fed through filters and the effect chain. the rest of the view doesn't seem to do much:
<img width="907" alt="surge_51-surge" src="https://user-images.githubusercontent.com/4966687/50661000-61223700-0faa-11e9-8932-0618a2d2012a.png">

(like the FM aspect etc).

**Comment by baconpaul** [comment]
I've been wanting to play with that. Seems like you could do some powerful processing. Does it work - can you route in input from a side chain in a host or some such?

**Comment by esaruoho** [comment]
@baconpaul .. here is a screenshot:
in this, track `tg` is sending it's output to track6Surge (Audio To) and Surge is receiving it as an audio input. the audio can then be fed through the effectchain and the filters. not much else tho.
<img width="154" alt="surge_6-surge" src="https://user-images.githubusercontent.com/4966687/50661302-55834000-0fab-11e9-8a6a-8121cd6da63d.png">

**Comment by esaruoho** [comment]
and with Logic Pro X, yes, you'd just use the "Sidechain" aspect to route audio into Surge.
<img width="907" alt="fullscreen_03_01_2019__23_04" src="https://user-images.githubusercontent.com/4966687/50661504-025dbd00-0fac-11e9-8ab3-f198bad04cb0.png">

...and TIL that Logic Pro X routes audio into plugins with that sidechain part.

**Comment by baconpaul** [comment]
lots of fun to be had with the logic pro side chain. ducking in compressors, fun with vocoders, etc.

**Comment by esaruoho** [comment]
i'm not entirely sure how to do the same with Renoise, though. i should look it up. anyway, having audio input working for logic pro x and live is good enough.

**Comment by esaruoho** [comment]
closing ticket since this is not "issue with surge" but more like "how to use surge" - so nothing to do with the repo itself.
