### ISSUE TITLE
Learn controller [MIDI] - needs testing

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#202]
![fullscreen_04_01_2019__10_21](https://user-images.githubusercontent.com/4966687/50679093-90689080-100a-11e9-8afd-4c7e7b560d6a.jpg)

right-clicking on a parameter will show `Learn controller [Midi]`. Good to check if this actually works.

**Comment by baconpaul** [comment]
This all works. I looked at the code when I was in MPE and just tested it this morning.

![learn-midi](https://user-images.githubusercontent.com/13387561/50694214-4336ef80-1007-11e9-88ed-e142a385cfe9.gif)

I'm going to close this issue. If there's a bug lets re-open it.
