### ISSUE TITLE
Mac binaries

### ISSUE THREAD

**Issue by nitelinejazz** [kurasu/surge#21]
Hello, what about mac version? I looking forward for it. TNX.

**Comment by kurasu** [comment]
duplicates #3

**Comment by esaruoho** [comment]
@nitelinejazz which format are you looking for? VST2/VST3 doesn't exist, but an experimental 64-bit AudioUnit version exists -- in fact, @baconpaul just wrote a PR for it, but even if it gets merged in, the building of a `Surge.component` requires a bit of work ( check https://www.kvraudio.com/forum/viewtopic.php?p=7254735#p7254735 for steps)

**Comment by nitelinejazz** [comment]
@esaruoho I am looking for AU. TNX!

**Comment by esaruoho** [comment]
@nitelinejazz send an email to esaruoho@gmail.com

**Comment by nitelinejazz** [comment]
Ok tnx:)

-- 
Waldemar Gołębski
www.nitelinejazz.com
+48 504779554
