### ISSUE TITLE
Documentation on Development (esp windows)

### ISSUE THREAD

**Issue by baconpaul** [kurasu/surge#215]
Folks:

The documentation on windows development is a little bare bones and being not that experienced in windows, I am missing things like "how to go from the built artifact to a running vst". Something like `build-osx.sh --build-and-install` isn't there.

I'm happy to write little scripts and update the README but I actually don't know the steps to take. So if you are developing on windows, how do you go from the result of your visual studio build to an installed VST which can show up in a host? Do you run the inno setup thing and double click the msi? do you copy some file? 

@kzantow @kurasu @esaruoho @asimilon - any hints appreciated!

If someone can add hints to this issue, I can try it out and update the docs. Thanks!

**Comment by esaruoho** [comment]
@baconpaul what about this stuff posted by @getdunne

https://github.com/kurasu/surge/issues/97#issuecomment-451170047

He wrote some rudimentary instructions there
