### ISSUE TITLE
Could we get a GUI scaler / zoom?

### ISSUE THREAD

**Issue by MBYlt** [kurasu/surge#22]
**Surge is great and incredibly powerful, but I hate squinting!**
It would be really nice if there was an option to resize the GUI, to make labels easier to read and to make it a bit easier to click the right areas during live situations. The best example I can think of off the top of my head is Serum, which allows you to set the GUI scale anywhere from 50% to 400%.

Doesn't have to look smooth or pretty, simple nearest-neighbor pixel doubling (quadrupling, octupling, etc) would be fine for those of us with high resolutions but whose monitors are far away from our performance hardware.

**Comment by funkaloss** [comment]
I agree. A somewhat scalable interface would be great.

**Comment by baconpaul** [comment]
Check out #81 for this. I have a prototype zoom working in the UI host. 

If you'd like to hop over there and perhaps close this issue, that would be great!

**Comment by MBYlt** [comment]
> Check out #81 for this. I have a prototype zoom working in the UI host.
> 
> If you'd like to hop over there and perhaps close this issue, that would be great!

So after spending the day getting acquainted with git/Visual Studio and finally getting your source to build (for some reason I randomly get malloc.h errors that sometimes vanish on a rebuild attempt, sometimes not - very odd, it's probably just me being a noob) I realized you only implemented this in the .AU, not the VST2/3... d'oh.

Anyway, the screenshots look nice, once this is merged to the .DLL/.VST3 I'll be happy to close this issue.

**Comment by baconpaul** [comment]
The problem to merge this into a .DLL or .VST3 is that someone has to write a resize callback in that host also. I only really have a mac/AU dev environment. It's not that hard, just I don't have the APIs or a test machine. If someone wants to take a shot at that, let me know (probably by tagging over in #81).

Sorry to not be clearer and making you go and build something that doesn't work! Apols.

**Comment by esaruoho** [comment]
Closed by #92 except for needing zoom for vst2/vst3

**Comment by esaruoho** [comment]
@baconpaul how's your experience with zooming with Surge re: using Logic Pro X's "View" feature?
![fullscreen_27_12_2018__10_49](https://user-images.githubusercontent.com/4966687/50473291-18c0b300-09c5-11e9-8adf-6fafeef7f4aa.jpg)

**Comment by baconpaul** [comment]
Let’s consolidate all the GUI scalar / zoom stuff into issue #23, since we are going to go the route of re-rendered multi-scale bitmap. Closing this one - but not because the feature isn’t happening but just to keep the conversation organized.
