### ISSUE TITLE
Please let's use GitHub "projects" 

### ISSUE THREAD

**Issue by cyanit** [kurasu/surge#222]
Just set up a To-Do list for an issue manually and it sucks. It's tedious, takes time and is not great for a quick overview. 
I like projects a lot more, its easier and you have a quick overview of current bugs, whats worked on and what needs to be done.

https://github.com/kurasu/surge/projects

**Comment by baconpaul** [comment]
Haven't used them but happy to do so. Want to set up a project for "vectorized UI with scalable zoom"?

As long as they have a number I can refer to in my branches I'm happy.

**Comment by cyanit** [comment]
Yes, but I can't (so someone else needs to do that please). Also, ideally choose a short name (Vector UI + Scaling) so there are no two line headers.

They probably have the ability to reference certain cards/topics. Its github, would be fatal if such a basic feature would be missing.

**Comment by itsmedavep** [comment]
Maybe just call it Vector UI.

Its all related to that.

**Comment by baconpaul** [comment]
Can you not do it because of time, or because of permission? Once its created can you edit it?

**Comment by baconpaul** [comment]
Anyway I created a project. All you guys! I'll close this issue.

If it turns out to be useful we can use it for other things too. Look forward to trying it out with you.

**Comment by itsmedavep** [comment]
> Anyway I created a project. All you guys! I'll close this issue.
> 
> If it turns out to be useful we can use it for other things too. Look forward to trying it out with you.

Doh. It's a permissions thing I think. I can see the board. But I cant see any of the things about creating bugs whatever that the help references.

**Comment by baconpaul** [comment]
I just see "add a column". I've never used these and I don't have permissions to change permissions.

So happy to do what you need but have no idea what to do.

**Comment by esaruoho** [comment]
@itsmedavep let's try and figure this one out. i'm a bit vague myself on the assets and how they are doing, whether everything is "behind the scenes" until PR, or if we're seeing commits per file change.

@itsmedavep maybe we could collab together on the differences between old+new-classic, i've posted some at #221 - i've tried to post some issues that are missing or somehow otherwise neglected.

**Comment by esaruoho** [comment]
about projects == it is just simply a glorified way of showing github issues. i've tried to use it in other projects and it just doesn't give any benefit, unless if everyone uses it. if only one person uses projects, then that one person is constantly sweeping + cleaning the project project, and it is just a timesink.

**Comment by baconpaul** [comment]
Ok so I'm glad for you guys to use issues however you want. I'm fine with issue per UI bug. I do prefer a PR maps to one issue but an issue having multiple prs is fine

But whatever works for you is cool with me!

**Comment by cyanit** [comment]
Okay, I think well just continue to use github as its intended.

However, I've quickly set up a slack+trello. This provides a decent platform for communication and collaboration. Personal stuff like the email should be hidden. The idea is to shorten the actual issues, yet be able to discuss them openly. It's open, so everyone can join.

[Slack workspace](https://join.slack.com/t/surgeteamworkspace/shared_invite/enQtNTE3NDIyMDc2ODgzLTU1MzZmMWZlYjkwMjk4NDY4ZjI3NDliMTFhMTZiM2ZmNjgxNjYzNGI0NGMxNTk2ZWJjNzgyMDcxODc2ZjZmY2Q)
[Trello board](https://trello.com/b/ncFvzbNa)


_@kurasu please contact me about the ownership/admin thing._

**Comment by baconpaul** [comment]
Cool I joined the slack. I also updated the README with a link to it.

Let me know if you want me to do anything with the project.

**Comment by kurasu** [comment]
> _@kurasu please contact me about the ownership/admin thing._

yeah what about it?

**Comment by cyanit** [comment]
Okay, you're on there. Transferred the ownership. Will close this now...
