### ISSUE TITLE
Vector Master File - Effects Routing Graphics Text Has Issue Where L - R text is kerned too much

### ISSUE THREAD

**Issue by itsmedavep** [kurasu/surge#225]
The effects routing graphics bmp0012.png text has this issue in the source file:

**From the source file:**
<img width="738" alt="screen shot 2019-01-06 at 12 19 35 am" src="https://user-images.githubusercontent.com/11078351/50732900-e5122580-1148-11e9-9fa4-db770653cf39.png">

It should be fixed in the master.

The GUI fix 1 has these corrected. So it would seem that the issue was caught but the master was not updated. Please close this as duplicate if it is accounted for in #221 

**From assets/export:**
![bmp00112 3x](https://user-images.githubusercontent.com/11078351/50732926-3a4e3700-1149-11e9-9cfe-dde904f88d0e.png)

**Comment by esaruoho** [comment]
which issue? pretend we're blind. i see that `L-R` crosses over to the other button..?

**Comment by cyanit** [comment]
I didn't even notice this, on my side everything looked fine and (as far as I remember) didn't have to fix anything. Maybe thats a bug in your version of affinity designer?

**Comment by itsmedavep** [comment]
Super weird. I dont see this issue any longer. 

Closing
