### ISSUE TITLE
Store patch dialog: Clicking on Name/Category can result in dialog forgetting changes

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#231]
Logic Pro X has the best bugs:

Steps to replicate:
1. Launch Surge
2. Click Store
Store Dialog opens.
3. Click on `Name`.
4. Type banana on `Name`.
5. Click on `Category`.
Expected result:
banana stays
Current result:
banana disappears
6. Type mango on `Category`
7. Click on `Name`
Expected result:
mango stays
Current result:
mango disappears.

Modified:
Type banana on `Name`.
Press Tab.
Type mango on `Category`
Press Tab.
Type avocado on `Creator`
Press Tab.
Type cucumber on `Comment`
Click `Name`

expected result:
cucumber stays
current result:
cucumber disappears

**Comment by esaruoho** [comment]
![surge_storer3](https://user-images.githubusercontent.com/4966687/50794640-57fbd780-12d4-11e9-8f0f-a8c612aea5f3.gif)
here's a better one.

**Comment by kurasu** [comment]
This code is new for 1.6, so its not been widely tested. The save dialog was previously implemented natively for both windows & osx but I converted it to just use the VSTGUI widgets to ease portability.

**Comment by baconpaul** [comment]
Interestingly, and terrifyingly, this is host dependent. 

For instance if I run it in logic what you say happens

But when I do the same in Hosting AU I get this

![hosting-au](https://user-images.githubusercontent.com/13387561/50798693-3d5f3980-12a7-11e9-9dda-20399ced9359.gif)

"cool".

ugh must be some intercept happening deep inside the vstgui which differentiates tab from return in some host contexts on mac. 

ugh.

**Comment by esaruoho** [comment]
@baconpaul further detail on Logic Pro X saving:

1. Press Store
2. Click on Name
3. Change name
4. Press OK

Result: Name is not changed.

Solution:

1. Press Store
2. Click on Name
3. Change name
4. Press Tab
5. Click OK

result: name is changed.

**Comment by baconpaul** [comment]
Yeah I took a minute last night to look at the ctext implementation. There is some focus handling stuff which looks like it may be the issue.

This one will be tricky to debug I think. It will stay open for a bit. I certainly won’t get to it soon
