### ISSUE TITLE
The Poly 0/8 does not update unless user clicks on Poly-area

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#234]
Steps to replicate:
1. Hold down a note
2. Watch Poly count
Expected result:
Poly count says `1/8`
Current result:
Poly count says `0/8`

3. Double-click on `0/8` while holding down note
Expected result:
Poly count says the right number of notes playing
Current result:
Poly count refreshes to `1/8`
4. Let go of note
Expected result:
Poly count says `0/8`
Current result:
Poly count says `1/8`
5. Hold down 4 notes
6. Double-click on Poly-counter-area
Poly counter updates to 3/8.

in essence, the poly counter is not "live", and only gets updated when you modify it's parameters.

**Comment by baconpaul** [comment]
That PR fixes this. Absent objections I'll merge it tomorrow night.
