### ISSUE TITLE
Poly count fluctuates and flickers to 0 while notes are playing (VST/AU)

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#248]
Logic AU + Live VST
![poly freakout2](https://user-images.githubusercontent.com/4966687/50925762-f5cdde80-145b-11e9-83ab-3a0d0cd4c753.gif)

i tried to up the framerate of the gif but not sure if it shows properly

**Comment by baconpaul** [comment]
I was able to see this in Hosting AU + AU also. The code looks correct and clear as day so I wonder what it is. Will require some debugging. Not an instant fix.

**Comment by baconpaul** [comment]
Oh this is a threading problem

Idle polls on ui thread
Value is updated on audio thread
Value is zeroed out and reincremenred each process
We grab in the middle

Easy to fix. Don’t update in place etc
