### ISSUE TITLE
[bug] Behaviour: Control name does not clear after selecting "clear all"

### ISSUE THREAD

**Issue by cyanit** [kurasu/surge#252]
If a control is set up, it is automatically named after the first parameter that it was assigned. 
If you right click on it, you can see all assignments and have the option to clear stuff.
![c-reset1](https://user-images.githubusercontent.com/26248671/50967593-d2954480-14d8-11e9-9cbc-7d3d06e4a5b0.PNG)

So, I clicked on "clear all". Why not.
![c-reset2](https://user-images.githubusercontent.com/26248671/50967595-d45f0800-14d8-11e9-8bf3-537a9187536f.PNG)

It cleared all, but the name stayed.
![c-reset3](https://user-images.githubusercontent.com/26248671/50967596-d5903500-14d8-11e9-84c8-2aeef08e21c3.PNG)

Even if you reassign a parameter, the old name stays.
![c-reset4](https://user-images.githubusercontent.com/26248671/50967783-7121a580-14d9-11e9-831e-f8fdbe2ef193.PNG)

This is definitely not something important, but it's confusing nonetheless.
I don't know if it's intended that way, but 
![bug report](https://user-images.githubusercontent.com/26248671/50968611-ed1ced00-14db-11e9-951f-96002a982036.png)

**System**
OS: Windows 10
Host: Bitwig Studio
Plugin: v1.6b3

**Comment by esaruoho** [comment]
now that you dropped this, i'll chime in. been seeing this. happens on macOS VST/AU too.

**Comment by baconpaul** [comment]
I'm sorry which step exactly seems like the bug here? I'm just not quite following.

**Comment by baconpaul** [comment]
And thanks for the clear screenshots! Just if you could let me know what you expect to be different in them that would really help. Appreciate it.

**Comment by cyanit** [comment]
Clicking “Clear All“:

**Ecpected**
- Clear assigned parameters
- reset name to “-“

**Reality**
- Clear assigned parameters
- name is still the same as before
Even if you re-assign the control, it won't rename (like it does when you assign it from its initial, emty “-“ state).

Sorry, but I thought is was obvious from the screenshots...

**Comment by esaruoho** [comment]
@baconpaul the really important thing is that the context menu is never updated. bind to one, becomes one. remove, bind to another one (two), stays previous-one.

**Comment by baconpaul** [comment]
I get @cyanit - clear should also rename (“-“)

I don’t get your comment @esaruoho

**Comment by esaruoho** [comment]
@baconpaul maybe this'll help
![surge_controller_renamev3](https://user-images.githubusercontent.com/4966687/51000992-4c5c1b00-1537-11e9-92fb-1e5f9e066bdb.gif)

**Comment by baconpaul** [comment]
Oh how's that different than @cyanit? or is it not?

Just "rename to - when you clear" yeah?

**Comment by cyanit** [comment]
@paul There's is no difference, its the same issue. Clearing the name should happen when you are cleaning all bindings.

**Comment by baconpaul** [comment]
Got it thanks

**Comment by baconpaul** [comment]
![reset](https://user-images.githubusercontent.com/13387561/51034931-5ea97980-1576-11e9-81fe-e579f5603190.gif)

This is the correct behavior right?

**Comment by baconpaul** [comment]
Also fixed. Thanks!
