### ISSUE TITLE
[bug] UI: Meter Is clipping only on the right channel

### ISSUE THREAD

**Issue by cyanit** [kurasu/surge#253]
I noticed the internal meter is not showing clipping correctly:
![clip-left-host](https://user-images.githubusercontent.com/26248671/50969640-6ec24a00-14df-11e9-9ff0-060673a04a9b.PNG)

In case you wondered how it looks panned ~90% left:
![clip-left-left](https://user-images.githubusercontent.com/26248671/50969700-8f8a9f80-14df-11e9-84d1-b4f349f55ede.PNG)

**System**
OS: Windows 10
Host: Bitwig Studio
Plugin: v1.6b3

**Comment by esaruoho** [comment]
now that you mention it, yep, i can confirm it happens on macOS VST / AU too.

**Comment by esaruoho** [comment]
@baconpaul here's a patch.
just press a regular note and hold it down.
you'll see the clipping.
if not, press and repress it 2-4 times

[patch_for_baconpaul.fxp.zip](https://github.com/kurasu/surge/files/2745482/patch_for_baconpaul.fxp.zip)

**Comment by cyanit** [comment]
Discobered this by wondering how efficient surge is, so I just used 64 notes simultaneously. Worked too.

**Comment by baconpaul** [comment]
Thanks. Fixed.

**Comment by cyanit** [comment]
wow, that was fast. Nice!

**Comment by baconpaul** [comment]
Thanks! It was a one line fix once I had a patch which clipped and a good bug report so thanks to you both
