### ISSUE TITLE
Next/Previous Patch/Category/Wavetable do not conform to A-Z sorting

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#269]
it would appear that the @jsakkine A-Z sorting for patches, is ignored when using the +/- to select next/previous patch.

First the Next/Previous Patch:

Steps to replicate:
1. Select `Bass` -> `Attacky` (first one)
2. Click on `+` 

Expected result:
`Bass 10`  is shown and ready to play

Current result:
`WTbass` is shown and ready to play.

3. Click on `+` again. 
Expected result:
the first Chord-category preset is loaded.
Current result:
`Bass` -> `Stable` is shown and ready to play.

`+` again -> `Pad` -> `Pad 5`

and so on.
![patch-change](https://user-images.githubusercontent.com/4966687/51051669-2721e800-15dd-11e9-9625-62d34a0ec5e6.gif)

Second:
Next/Previous Category:
Steps to replicate
1. Select a Bass patch
2. Click "+". on Category.
Expected result:
Chord
Current result:
Pad

Press +, get Percussion. Press +, get Polysynth. Press +, get Pad (choir), 
`+` = Vocoder.
`+` = Pad (animated)
`+` = Pluck (fast)
`+` = Sequence
`+` = Chord
`+` = Keyboard
`+` = inigo_kennedy_01
`+` = Argitoth
`+` = Giana-Brotherz
`+` = Bluelight
`+` = Noisegeek
`+` = Rozzer

and so on.

**Comment by jsakkine** [comment]
Really appreciate the level of detail that you go with your reports!

**Comment by esaruoho** [comment]
@jsakkine my pleasure :)

**Comment by baconpaul** [comment]
Great! Around line 1965 of surgeguieditor.cpp is where the event gets handled in case you haven’t traced through the event code yet.

**Comment by esaruoho** [comment]
@baconpaul you were right. the wavetables next/back also doesn't work accurately.
update:
the arrow right in wavetables, when your selected wavetable is "pmfreq" and you press arrow right, you get "sine windowed".. not "primes".


<img width="707" alt="fullscreen_13_01_2019__16_02" src="https://user-images.githubusercontent.com/4966687/51086228-c74a4f00-174c-11e9-8667-2bbef8ccb6c9.png">

**Comment by jsakkine** [comment]
OK was a bit busy weekend. I'll look into this tonight.

**Comment by jsakkine** [comment]
I'll work on a wavetable PR now while waiting #307 and #308 progress and pause Linux work for a short while.

**Comment by esaruoho** [comment]
fixed by #312 (wavetable part).. once that is merged in, this ticket can be closed. i've left a continuation ticket (#314) for preset category-cross +/-.

**Comment by jsakkine** [comment]
Can we close this now?

**Comment by baconpaul** [comment]
Yup

**Comment by jsakkine** [comment]
Finally.
