### ISSUE TITLE
HP does not go to 0 (instead 6.875Hz), and then 1046.502Hz at the top.

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#275]
when moving the HP slider to the bottom, it shoots `6.875Hz` and when moving it to the top, it shoots `1046.502Hz`. not sure what's going on with these. Why can't I get the Surge HP to go to 0Hz HP?

![weird hp parameter numbers](https://user-images.githubusercontent.com/4966687/51061428-f56c4980-15fb-11e9-9d90-3302729a9875.gif)

**Comment by kurasu** [comment]
The values are given in a logarithimc scale, so it can't reach zero (unless the slider it's infinitely long). So to "solve" this,someone would need to make it jump to by passing the filter at the lowest setting (And show 0 in that case). It would also need to make sure this happens without any clicks, but that could be doable by producing filter coefficients which are essentially bypass the filter but still processing it.

**Comment by esaruoho** [comment]
agreed, closing ticket!
