### ISSUE TITLE
Wavetable right click menu doesn't work

### ISSUE THREAD

**Issue by really-need-an-api-key** [kurasu/surge#29]
**Describe the bug**
No context menu (containing all the wavetables for easy selection) is shown when right-clicking the wavetable name.

**To Reproduce**
1. Right-click on the wavetable name.

**Expected behavior**
Right clicking the wavetable name should open a context menu with all the wavetables.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Host: FL Studio 12
 - Version: 12.0.5

**Additional context**
Context menu doesn't work in VSTHost either. Switching via the tiny arrows works though.

**Comment by baconpaul** [comment]
This is literally a one line change. Looks like the rewrite of the context menu just forgot to call popup

I have fixed it in 

https://github.com/baconpaul/surge/commit/d404bdd04b9660a904e793ba85ecd75c5d5129f6

but I can't send a pull request for that until #69 is merged

**Comment by baconpaul** [comment]
<img width="419" alt="screen shot 2018-12-14 at 3 00 06 pm" src="https://user-images.githubusercontent.com/13387561/50024616-fa17f080-ffb0-11e8-8f75-a9d66023e54d.png">

Oh that "." and ".." is because the mac stub of std::filesystem implements

**Comment by baconpaul** [comment]
sorry because std::filesystem implements the iterator wrong so I have a new issue for that in #77

**Comment by esaruoho** [comment]
> This is literally a one line change. Looks like the rewrite of the context menu just forgot to call popup
> I have fixed it in
> [baconpaul@d404bdd](https://github.com/baconpaul/surge/commit/d404bdd04b9660a904e793ba85ecd75c5d5129f6)
> but I can't send a pull request for that until #69 is merged

@baconpaul can this one-line fix be added into #69 ?

**Comment by baconpaul** [comment]
Oh sure I guess it could! But since this may also impact VST I sort of left it aside.

Also, my local dev area is a bit of a mess right now because I'm working on a zoomable UI so let me keep my brain there for now.

**Comment by asimilon** [comment]
Not sure if it's the best, but it fits the "free" criteria : https://www.tracktion.com/products/t7-daw

**Comment by baconpaul** [comment]
Yeah best is definitely an opinion! Also we all know emacs is the best. We just need M-x daw-mode to get finished. 

Thanks!

**Comment by esaruoho** [comment]
@baconpaul i added your fix to this into my larger PR #68 . hope that's fine

**Comment by esaruoho** [comment]
👍
