### ISSUE TITLE
macos installer: ~/Library/Application Support/Surge is not updated if it already is there (and you have extra wavetables there f.ex.)

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#290]
as per discussion with @baconpaul - yep, the macOS installer has a similar bug as a previously mentioned+fixed bug.

Steps to replicate:
1. copy custom wavetables to `~/Library/Application Support/Surge/wavetables`
2. quit all audio apps
3. install new version of Surge with macOS installer

Expected result:
new content added by the installer to `~/Library/Application Support/Surge`

current result:
no new content added, left as-is.

only solution is to kill the Surge folder. and then install

**Comment by baconpaul** [comment]
This is the resources sub installer. The big pkg contains 4 subs and the resources sub needs fixing like we fixed component vst and so on
