### ISSUE TITLE
bash script knowhow request: osx-baker function for .dotfiles

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#291]
hi guys, i'm trying to streamline my testing and am trying to just run one command on the terminal that 1) cleans 2) builds 3) makes an installerwith randomized name 4) opens the installer in the folder it has been placed into.

this is where i'm at now, i'm trying to use `$DATE` (not that i know why this would work, or why it wouldn't work)

```
function surgebake
{
cd ~/work/surge
cd ~/work/surge
./build-osx.sh --clean-all
./build-osx.sh
cd installer_mac
./make_installer.sh $DATE
cd installer
open .
}
```

what should i input into that $DATE portion to make it be a time-based name, or random? should i do this some other way?

**Comment by esaruoho** [comment]
```
function surgebake
{
export surge-folder=~/work/surge
cd $surge-folder
cd $surge-folder
./build-osx.sh --clean-all
./build-osx.sh
cd installer_mac
./make_installer.sh "$(date +%Y-%m-%d-%H:%M:%S)"
cd installer
open .
}
``` maybe.

**Comment by esaruoho** [comment]
solved! thanks heaps @kzantow

**Comment by baconpaul** [comment]
I was actually going to add exactly this to build osx- something like build-osx—clean-and-package

Will do it when I’m fixing resources instsller
