### ISSUE TITLE
proposal: automatic builds could use --date - improvement for ./make_installer.sh

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#292]
proposal, improve `installer_mac/make_installer.sh`  by adding `--date` as a switch.

`--date` would be `"$(date +%Y-%m-%d-%H-%M-%S)"`

this way the built packager is called
`Surge-2019-01-12-23-15-55-Setup.pkg`

thoughts, @kzantow @baconpaul 

...i think i heard some talk about wanting to have the date+time of build in the file itself.
would this help somehow?

**Comment by baconpaul** [comment]
As I said on slack, I think the right name is

Surge 1.6beta 20190112.dmg

or some such. We don't need the time But we do need that 1.6beta.

**Comment by baconpaul** [comment]
I don't want to put this in make-installer but there's a diff coming soon that will add it to build-osx so you get a one-step.

Basically

```
build-osx.sh --clean-and-package
```

cleans down everything and makes a package and puts in in product with a good name.

```
build-osx.sh --package
```

just runs the packaging.

**Comment by baconpaul** [comment]
Oh and so I closed this since it's going in build-osx.
