### ISSUE TITLE
feature Request: Independent Envelopes for Each Oscillator

### ISSUE THREAD

**Issue by sense-amr** [kurasu/surge#303]
I believe the sonic capability of Surge could be greatly improved by allowing independent envelopes for Filter and Amp .. for each oscillator .. i dont know how difficult this would be to code into the existing builds.. but i do know it would offer greater sonic exploration and synthesis capabilities of what is already shaping up to be a great synth..

**Comment by baconpaul** [comment]
@sense-amr thanks for both this and #302. As we chatted about on slack last night, I think we should leave feature requests until after we get a 1.6.0 non beta build running linux and win vst2/3 and mac vst2/3/au 64 bit with bugs fixed. At that point sort of 'declare a mini victory' then look at new features. So I'm going to tag both of these, and also my feature request I'm about to put in, as 'feature request' 'future version'.

I like this idea. One way you could do it, btw, is have a LFO-type which is "ADSR Envelope". There are enough LFOs around. Then apply that to oscillator volume and have a master envelope bypass of some form. Just a thought.

**Comment by sense-amr** [comment]
Thanks Paul, i don't really know what i'm doing with the right way to request things here.. but i thought i might as well give it a go after some encouragement from esaruoho .. so i guess my request is definitely a "future" request .. in line with improving on surge .. rather than fixing current issues.. i hope i didnt post in the wrong place ! :)

**Comment by baconpaul** [comment]
Oh yeah putting it in as an issue is perfect! Just letting you know why I tagged it (and letting other readers know also). So lets pile them into issues but if we apply the tag it means we can filter them out when looking for 'must fix' things. Sorry didn't mean to give the wrong impression!

**Comment by sense-amr** [comment]
heh nah man like i say i have no idea how this stuff works .. just pretty much shooting ideas out there based on my experience from using Surge :) .. i leave it to you to handle the correct area for collating such ideas!

**Comment by baconpaul** [comment]
"One Github Issue Per Idea" is perfect I think. Because then there's one PR and one design place for it.

**Comment by sense-amr** [comment]
makes sense to me :)

**Comment by kurasu** [comment]
You can use any of the LFOs in envelope mode, and assign them to anything.. and filter and amp can't be separate because the oscillators are summed together before the filter, so you'd be talking about a totally differe

**Comment by sense-amr** [comment]
can you please give an example of how to make each envelope have an independent filter and amp envelope in a practical way ? @kurasu

**Comment by baconpaul** [comment]
Filter is trickier but amp - put lfo in envelope mode and bind it to the mix level right?

For filter there are 2 filters per scene and you can control them with an lfo and route each osc to one or either

No?
