### ISSUE TITLE
surge-au: funknown.h/smartpointer.h/coreiids.cpp/iupdatehandler.h reference pluginterfaces/base/ how to fix?

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#31]
Four files within the `vst3sdk/pluginterfaces/base` folder try to include files in the subfolder `pluginterfaces/base` ( so basically referencing `vst3sdk/pluginterfaces/base/pluginterfaces/base` ).

The files in question are the following:

*funknown.h* references
```
#include "pluginterfaces/base/fplatform.h"
#include "pluginterfaces/base/ftypes.h"
#include "pluginterfaces/base/smartpointer.h"
```

`smartpointer.h` references

```
#include "pluginterfaces/base/fplatform.h"
```

`coreiids.cpp` references

```
#include "pluginterfaces/base/funknown.h"
#include "pluginterfaces/base/iupdatehandler.h"
#include "pluginterfaces/base/icloneable.h"
#include "pluginterfaces/base/ibstream.h"
```

`iupdatehandler.h` references

```
#include "pluginterfaces/base/funknown.h"
```

All these issues "seem to get fixed" by removing `pluginterfaces/base/` from the include.
but how does something like this get fixed in the repo however? 

<img width="746" alt="48972267-9fcde480-f02f-11e8-830b-0f65261d66e3" src="https://user-images.githubusercontent.com/4966687/48972463-90e93100-f033-11e8-8bd0-37ff12174755.png">

```
In file included from /Users/esaruoho/work/surge/vst3sdk/pluginterfaces/base/funknown.cpp:17:
/Users/esaruoho/work/surge/vst3sdk/pluginterfaces/base/funknown.h:19:10: fatal error: 'pluginterfaces/base/fplatform.h' file not found
#include "pluginterfaces/base/fplatform.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by esaruoho** [comment]
i mean, in the repo itself. if they are referenced from outside of the repo (submodules)?

**Comment by esaruoho** [comment]
`smartpointer.h` also references..

```
#include "pluginterfaces/base/fplatform.h"
```

and the error it shoots is erased by simply removing `pluginterfaces/base/` from the mix.

**Comment by esaruoho** [comment]
`coreiids.cpp` references

```
#include "pluginterfaces/base/funknown.h"
#include "pluginterfaces/base/iupdatehandler.h"
#include "pluginterfaces/base/icloneable.h"
#include "pluginterfaces/base/ibstream.h"
```

and the errors shot vanish by simply removing `pluginterfaces/base/` from the mix.

**Comment by esaruoho** [comment]
`iupdatehandler.h` references.. you guessed it..

```
#include "pluginterfaces/base/funknown.h"
```

and there i go removing `pluginterfaces/base/` from the mix, again.

**Comment by esaruoho** [comment]
location of these files is:
`vst3sdk/pluginterfaces/base` so not sure how to fix these issues since they are fetched from the vst3sdk repo..?

**Comment by esaruoho** [comment]
clarified original post a bit

**Comment by baconpaul** [comment]
Ho @esaruoho the problem is that in the AU build in Xcode that vst3sdk isn't in the header search path, just vst3sdk/vstgui4. With the addition of vst3sdk to the header path I get a lot further in the build. (plugin.h still breaks as we discussed in #49)

<img width="762" alt="screen shot 2018-12-08 at 8 21 11 am" src="https://user-images.githubusercontent.com/13387561/49686587-98ddb200-fac4-11e8-9945-42cadbb26dc2.png">

I don't really quite know my way around the premake.lua yet but I guess we just need to add this include directory there to get the build going further

**Comment by esaruoho** [comment]
@baconpaul 
hmm, i could try adding vst3sdk into the mix. let's see.

**Comment by baconpaul** [comment]
#59 has fixed this so I think we can close it. Thanks!

**Comment by esaruoho** [comment]
closing :)
