### ISSUE TITLE
Compiling with Xcode 10.1

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#32]
So, I started with these:

- Grab  `premake5` from https://premake.github.io . 
- Copy `premake5` to `/usr/local/bin/premake5`
- Clone the Surge repo by typing `git clone https://github.com/kurasu/surge.git`
- Get all submodules `git submodule update --init --recursive`
- Boot up Xcode and open, indexes, processes.
- Click on `Update to recommended settings` for `surge-au` -> Choose `Perform Changes`
- Click on `Update to recommended settings` for `surge-vst2` -> Choose `Perform Changes`
- Click on `Update to recommended settings` for `surge-vst3` -> Choose `Perform Changes`

After this, Xcode says:

`surge-vst2` `pluginterfaces/vst2.x/aeffect.h file not found`

`surge-vst3` `Use of undeclared identifier 'kHorizontal' in SurgePatch.app` (and Apple Clang error, too many errors emitted, stopping now)`

`surge-au`  `plugin.h file not found (called by aulayer.h, in file aulayer_presets.cpp:1:`. (isolated to #34  )

however, at least we're up and running, somewhat.

How do I fix these issues, please? These don't seem to be referenced in #3 so please don't close this ticket, please, @kurasu :)

**Comment by esaruoho** [comment]
surge-vst3 says
<img width="1392" alt="surgevst3processor_cpp" src="https://user-images.githubusercontent.com/4966687/48983024-7a55df00-f0f2-11e8-9c70-1e55ff14a14d.png">

**Comment by esaruoho** [comment]
surge-vst3 also says

<img width="1393" alt="surgevst3processor_cpp" src="https://user-images.githubusercontent.com/4966687/48983025-8346b080-f0f2-11e8-9778-8ba0b5ed95ce.png">

**Comment by esaruoho** [comment]
this `wchar_t *` has been mentioned by @kurasu in this issue:
https://github.com/kurasu/surge/issues/3#issuecomment-424832588

**Comment by baconpaul** [comment]
#59 fixes most of this so perhaps we should close it and have a different master issue for VST on Mac? Thanks!

**Comment by esaruoho** [comment]
closing
