### ISSUE TITLE
Remove VST 2.x SDK files

### ISSUE THREAD

**Issue by scheffle** [kurasu/surge#41]
The repository includes a submodule to the VST 2.x SDK files, which is not allowed.
See the license in the header:

// This Software Development Kit may not be distributed in parts or its entirety  
// without prior written agreement by Steinberg Media Technologies GmbH.

**Comment by esaruoho** [comment]
@scheffle what is the solution to this issue?

**Comment by kjyv** [comment]
It should not be a problem to include a submodule to something, it's basically a link.
The copy in the repository that is being linked is doing something against that license.
However, there is no VST 2 SDK anymore from Steinberg directly AFAIK as it is deprecated and not being supported anymore. This might hence be a legally gray area.

**Comment by abique** [comment]
@scheffle does the vst2wrapper let surge offer a vst2 interface out of its vst3 interface?
Otherwise surge would have to drop vst2.

**Comment by kjyv** [comment]
Apparently they also removed vst2 support from the vst3 sdk: https://www.steinberg.net/en/newsandevents/news/newsdetail/article/vst-2-coming-to-an-end-4727.html

**Comment by scheffle** [comment]
The license does not permit the VST 2x code to be redistributed, even if the actual code is in a submodule linked to another repository. This was always the case since the beginning of VST and nothing new. Most other projects solve this by letting the "builder" provide the necessary files by its own.

**Comment by ejgallego** [comment]
> The license does not permit the VST 2x code to be redistributed, even if the actual code is in a submodule linked to another repository.

Obviously adding a submodule , which is little more than a hash is not redistributing anything.

**Comment by kurasu** [comment]
I will change this to require providing an environment variable pointing to a local SDK when building the VST2 version.

**Comment by esaruoho** [comment]
@scheffle still excited to find out how to bake a vst2 within steinberg's limitations?
