### ISSUE TITLE
iPhone has denied to launch the app

### ISSUE THREAD

**Issue by zakria257** [kurasu/surge#43]
Hello

I'm new at iOS development so far. For now, i'm using Xcode 10.1 on MacBook Air'13 with apple developer id and iOS 12.1 on iPhone7. App is crashing when it is launched and displays the message "iPhone has denied to launch the app."

Previously i was using macOS High Sierra but now when I've updated to Mojave 10.14.1 and reinstalled Xcode 10.1, it's still showing the same error. 
Moreover, I've tried all the other solutions available on Google but nothing is worth it!
Is there any way to cope with this problem?

**Comment by esaruoho** [comment]
@zakria257 query, is this VST / AudioUnit Plugin supposed to be launchable with an iOS device?

**Comment by zakria257** [comment]
@esaruoho The issue has been resolved. It required a certificate setting to be changed.
Thank you

**Comment by zakria257** [comment]
What did you mean by Surge? @esaruoho

**Comment by esaruoho** [comment]
@zakria257 are you sure you're not in the wrong repo? this is for the VST2/VST3/audioUnit plugin Surge, by Vember Audio? You are at http://github.com/kurasu/surge and leaving comments there.

**Comment by zakria257** [comment]
@esaruoho oops. I've just posted at wrong repo.
Apologies!

**Comment by esaruoho** [comment]
@zakria257 could you close this issue, please? :)

**Comment by esaruoho** [comment]
@abique maybe you can close this ticket since it is not Surge related in any way.

**Comment by esaruoho** [comment]
@zakria257 hi, could you please visit this ticket of yours, and click "close", since it is not related to the Surge repo? No use having tickets stay open that are not related to Surge. Right? Thanks! :)

**Comment by esaruoho** [comment]
@kurasu could you close this ticket, please?
