### ISSUE TITLE
Create the CocoaUI rather than CarbonUI for the audio unit

### ISSUE THREAD

**Issue by baconpaul** [kurasu/surge#61]
Following the work in #58 and the subsequent pull request in #59 I can build an audio unit on my mac which opens in logic and plays sounds and switches between presets, but has no UI. That's all in that PR or you can get it on the @baconpaul fork of Surge on branch au-build.

So I have done a branch off of that branch to get the ui working, called au-build-ui. It contains all of au-build (so makes a working plugin) but also starts including the work to go from carbon to cocoa. As of now, it has the hooks to successfully have the AUVal tool ask for a cocoa UI, and then when it asks for the UI, enter objective c code, do something with the cocoa runtime (in this case, leak an NSURL), fprintf to stderr, and then go on its way with no UI. You know, small steps. But premake5.lua generates the Xcode to include the objective C and the two interoperate and link and run, so I should be, in theory, off to the races to bounce back and forth.

My basic plan of attack now I have this working is to figure out how vstgui and nsview interact using some combination of the vst sdk source, a worked example in a juce plugin, and a few other places. I hope, have the vstgui stuff all work "eventually" using the subclass trick that's already in the SurgeGUIWhatzit class. I'll keep notes here as well as a record of what I did if anything works or if I have anything working. But if someone reading this has done what I'm about to try before, please do let me know!  And if you actually know how to do this, aulayer_cocoaui.mm in src/au on that branch is the place to be. 

Finally if maintainers don't want me keeping record of how I got this thing working in GitHub issues please do just let me know. Apologies if the intermediate steps are too spammy.

**Comment by esaruoho** [comment]
hi @baconpaul did you see that @kurasu merged in #59 ? :) awesome! looks like your `au-build-ui` could then, instead of being a further commit into the #59 - be a separate PR altogether.

what did you think of what Claes Johanson did to your PR in the end? Seemed like pretty minor fixes.

**Comment by baconpaul** [comment]
It's all great! Thanks @kurasu 

And yes, @esaruoho now that au-build is merged I can take my cocoa stuff and do a fresh branch of the head of master. I just did that. So au-build and au-build-ui are both now dead. In baconpaul/surge there is now a branch au-cocoaui-build which has as far as I have gotten on cocoa forked off the PR post #59. So if the UI works, I would do a new pull request.

**Comment by baconpaul** [comment]
So OK, I have actually done some of the plumbing. Here's a screenshot:

<img width="1565" alt="screen shot 2018-12-13 at 7 17 03 am" src="https://user-images.githubusercontent.com/13387561/49938243-555dbc00-fea7-11e8-9684-2cbf3ff07737.png">

@esaruoho as discussed in #66 this lets us play with parameters which are otherwise unexposed.

It's all on baconpaul/au-cocoaui-build but I strongly suggest no-one run that thread because

1. sizing is off. As you can see from the red border I paint
2. The idle thread isn't running so it only barely works. If a parameter has an effect on another it doesn't update the param list changes needed
3. I have a mistake somewhere in my objective c object lifetime so it causes crashes; Logic reliably crashes on exit and AU Lab reliably crashes on entry. So who knows what's going on. And the crashes can be bad for other audio stuff.

So really don't use this **unless** you are an expert objective C programmer who can help with the third item or your desire to try a half-implemented surge ui trumps your desire to have a stable system! Chuckle.

**Comment by baconpaul** [comment]
Oh hey sizing was easy. Pushed that too. Off for the day now.

<img width="1150" alt="screen shot 2018-12-13 at 7 40 32 am" src="https://user-images.githubusercontent.com/13387561/49939329-84296180-feaa-11e8-999a-c5dfc0b4960c.png">

**Comment by baconpaul** [comment]
OK great I made a lot of progress now, although still not ready for a PR and still has some known crashes. But I fixed my 3 problems (sizing, startup crash, and idle loop) and now the UI actually really works. VU meter bounces, clicking buttons change things, etc...

There's still some bugs

1. If you close the window you get an instant crash because I'm not stopping the idle thread or doing any releases in the destructor path.
2. I think there's some places where I'm over-retaining or reference leaking

but if you build baconpaul surge on thread au-cocoaui-build using the full build instructions on the README and stuff, you should be able to run and play with the UI, as long as you never close it.

@esaruoho I don't suppose you'd like to try that would you and let me know if it also works for you? My cocoa programming skill level is "not high" so a second check that at least you can see what I see would be lovely.

**Comment by baconpaul** [comment]
And hey I got those two fixed also! This actually means the plugin - on my mac, built from source, with my hacky install script - works perfectly. I can open and close the instrument, switch it to another one and back, all those things, and no problem. I can also use the UI to do modulation.

And now my goal of "hey I wonder if this synth is any good" has been met. What a need modulation architecture!

Before I do a pull request I want to clean up and document the AU code a bit. I'll probably add a "doc" folder along with some of my notes as I went too. 

But @esaruoho you can build from my branch and you should in theory get a perfectly working Surge on 64 bit au macOS. Would love to know if you do!

**Comment by esaruoho** [comment]
Hi @baconpaul - i'm currently installing Logic Pro X so can try out your version of the AU and see what happens.

**Comment by baconpaul** [comment]
Cool @esaruoho - garage band shouldnalso work and is free too but appreciate the look!

**Comment by esaruoho** [comment]
@baconpaul hmm.. i have a question about how-to-do this.

So, first I get your branch, then do the whole submodules business - then run ./build-osx.sh - then i get a succeeded, then i go to xcode, open the project, validate all the extras in AU, clean, build.. and then the component is in products/ right?

Or, should I just run ./build-osx.sh and then copy the component to the plugin folder? What am I missing?

**Comment by esaruoho** [comment]
@baconpaul so far i don't see your PR referencing `README.md` updates. I'll run the xcode validate+clean+build and then run `./installer-local-au.sh`

I pushed a tiny update to my swedish language PR that changes one line in the `package-au.sh` to talk about AudioUnits (AU) instead of VST. Hope @kurasu will let it in :)

**Comment by baconpaul** [comment]
https://github.com/baconpaul/surge/blob/au-cocoaui-build/README.md

I think the prior pr had it; I see readme md has the info in building OS X section here. When all the pr are settled I’ll look again.

**Comment by esaruoho** [comment]
Thanks! Sorry.

Ok, so from my end, I'm able to get a Surge.component. I copy it to the Components folder in the Plugins-folder. The validation works a-ok, passes all validations, so it should be valid.

But I can't get Renoise OR Logic Pro X to actually display it as a plugin in the selector.

This confuses me. I thought I knew how to boot up AudioUnits no hassle. What might I be doing wrong?

I'm following all the steps in `README.md` - get the repo, go to the branch, get the submodules, run build-osx.sh, get to xcode, validate, clean, build, `./installer-local-au.sh` - the Surge.component is there in the Components folder.. .. .. why amn't i making progress? is there some extra step i'm neglecting? sorry about this!

@baconpaul

**Comment by esaruoho** [comment]
The only warning I get in auval is
```
WARM:
Time to open AudioUnit:         0.021  ms
load_wt_wt: reading the wavetable data failed.
load_wt_wt: reading the wavetable data failed.
load_wt_wt: reading the wavetable data failed.
load_wt_wt: reading the wavetable data failed.
```

but that's probably fine, right? after all, it's just a warning.

**Comment by esaruoho** [comment]
it must have been an user error. i'm recreating a branch and pulling your branch into it and trying the process again.

**Comment by baconpaul** [comment]
Yeah don’t copy by hand. Use the installer script

You may also need to blow your au cache. That’s in the readme

Offline for 6 hours so won’t be responding for a bit - thanks!

**Comment by esaruoho** [comment]
confirmed, after blowing the au cache, i got logic pro x to show me surge.

Renoise, for some reason, doesn't. When I get home, I'll check if Ableton Live shows it. Isn't it weird that Renoise wouldn't show it but Logic would? *mindexplodes*

**Comment by esaruoho** [comment]
awesome! feels like i should close this ticket #66 because i'm able to chain efx and trigger filters and whatever.

p.s. is there any chance of setting the filters to default to lo-pass, instead of "off"? :) 
p.p.s. i think it's time to find the documentation for this plugin and learn to use it because i have no idea how the routing works.

**Comment by baconpaul** [comment]
Here’s how routing works as I found out

Click the blue box that says lfo1 
It will turn a different color and get a little glyph. 
Then drag some slider and two sliders will appear
Lfo1 is now moving you between the two sliders

Etc

It’s cool. It kinda reminds me of how the drag to change works in equator

**Comment by baconpaul** [comment]
I’ve never used Renoise but the Internet seems to indicate it has its own audio unit cache which you can reset in preferences

http://forum.renoise.com/index.php/topic/50381-audiounit-plugin-ignored-but-loaded-in-other-daws/

**Comment by esaruoho** [comment]
@baconpaul thanks for taking the time to explain it! got how to do it after reading what you wrote.

So, so far:
Surge AU I've looked at with:
- Logic Pro X (can add chained efx into it)
- Ableton Live 10 (can't add chained efx into it)..

I don't have a lot of DAWs on this machine, but will try Renoise one more time.

**Comment by baconpaul** [comment]
OK so closing this issue now since it is all merged. I confirmed that a pull of kurasu/surge master and following the instructions in the README ends up with an AU which has a UI and which works!
