### ISSUE TITLE
Linux: VST2 plugin almost takes down the machine

### ISSUE THREAD

**Issue by jsakkine** [kurasu/surge#71]
The VST2 plugin loads now but I get a flood of these when I try to activate it:

```
Renoise Plugin Server LOG> VstPlugs: Caught exception in VSTPlug::ParameterValue
Implement me, probably
```

And then Renoise eats up almost all resource of my machine and I have to kill the process.

**Comment by esaruoho** [comment]
@jsakkine do you have instructions how to compile it on linux? Does it show the UI?

**Comment by jsakkine** [comment]
The first message comes from the VST host implementation of Renoise. The second log message is emitted by `SurgeStorage.cpp:134`.

**Comment by jsakkine** [comment]
```
$ git grep "Implement me, probably"
src/common/SurgeStorage.cpp:   printf("Implement me, probably\n");
```

**Comment by jsakkine** [comment]
I'll go through all the code paths without a Linux specific code path and see where it hugs up (the reason I created #90, would speed by factors if we had that).

**Comment by unfa** [comment]
Isn't the VST2 SDK going to be unobtainable, since Steinberg have axed the standard?

**Comment by jsakkine** [comment]
I'll close this issue as I'm working on the standalone app now.
