### ISSUE TITLE
KVR Audio form is not open for new accounts

### ISSUE THREAD

**Issue by jsakkine** [kurasu/surge#72]
_"An error occurred! To register a new account at KVR Audio please contact us with your username and email address and we'll check it out."_

I.e. **README.md** should include instructions how to contact KVR Audio. Otherwise, it is impossible to create an account and participate to the development discussions.

**Comment by esaruoho** [comment]
I would vote for removal of the KVR-Audio-Developer URL then, if it's 1) locked down AND 2) very silent.

it is, after all, VERY silent re: Surge.

**Comment by esaruoho** [comment]
#92 closes this (removal of kvr dsp audio URL from README.md)
