### ISSUE TITLE
std::filesystem stub on macOS returns . and .. in directory iteration

### ISSUE THREAD

**Issue by baconpaul** [kurasu/surge#77]
So std::filesystem isn't on Xcode 10 and the surge has a stubbed out implementation. I fixed a few bugs to get things running but directory iteration still returns "." and ".." in a way which leads to it showing up in menus.

<img width="419" alt="screen shot 2018-12-14 at 3 00 06 pm" src="https://user-images.githubusercontent.com/13387561/50024670-29c6f880-ffb1-11e8-87df-7f409f6bddbe.png">
<img width="611" alt="screen shot 2018-12-14 at 3 01 52 pm" src="https://user-images.githubusercontent.com/13387561/50024683-377c7e00-ffb1-11e8-8b28-b292e338ecc2.png">

So the trick is to filter appropriately in the hand crafted mac only directory iterator.

**Comment by esaruoho** [comment]
how would this be fixed, btw? i was wondering about `.` and `..` :)

**Comment by kzantow** [comment]
This is my fault, i'm fixing it now

**Comment by kzantow** [comment]
I can't seem to assign to me or anything, and i'm lazy so i'll just add it to #87

**Comment by baconpaul** [comment]
Thanks! Let me know when you have a commit and I'll merge it into my working copy.

**Comment by esaruoho** [comment]
@kzantow i don't see it on #87 as of right now.. can you make a separate PR that fixes this, please? :)
or link me to a commit and i can add it to #68

**Comment by kzantow** [comment]
@esaruoho fix is https://github.com/kurasu/surge/pull/87/commits/7be524369a4226c54dffad40b85eef63ecb5f8f0
