### ISSUE TITLE
Does original documentation of Surge exist somewhere?

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#78]
@kurasu @abique 

A question for you guys - any ideas if original documentation of Surge might exist somewhere on your drives?

I am, of course, referring to the contents of http://vemberaudio.se/download/surge.pdf

I'm ready to type it up to Markdown format by hand, but would rather not, if such documentation exists already. It's no bother if it doesn't, but just trying to find out if it's there or not first before embarking on this endeavour.

**Comment by kurasu** [comment]
I just added the original file to the repo
