### ISSUE TITLE
Surge-VST2: (macOS) Non-constant-expression cannot be narrowed from type 'int' to 'char' in initializer list

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#79]
am trying to get macOS VST2 to compile and am getting this error in audioeffect.cpp:
```
Non-constant-expression cannot be narrowed from type 'int' to 'char' in initializer list
```
<img width="833" alt="audioeffect_cpp" src="https://user-images.githubusercontent.com/4966687/50027422-dbd3e400-fff4-11e8-86d3-67aee3356c55.png">

What should I do about it?

**Comment by esaruoho** [comment]
Xcode suggests fixing it, so.. if I click on Fix, this:

```
char temp[2] = {'0' + (char)digit, '\0'};
```

changes into this:

```
char temp[2] =static_cast<char>( {'0' + (char)dig)it, '\0'};
```

is this overall something safe that I can commit to the repo?

**Comment by baconpaul** [comment]
That change is OK but a bit weird looking. If I were reviewing the code I would suggest you make it clearer with

```
Char tmp[ 2 ];
Tmp[ 0 ] = (char)( ‘0’ + (char) digit ); // so 0-9 goes to ‘0’ - ‘9’; and 10 goes to ‘a’
Tmp[ 1 ] = ‘\0’;
```

Which is basically the same thing just a bit more readable. I’d also ask if someone had confirmed that 0 <= digit < 10 somewhere earlier in the code.

**Comment by esaruoho** [comment]
@asimilon how did you solve this issue on your branch? :o

**Comment by asimilon** [comment]
The only source changes I had to make were removing `experimental::` from `std::filesystem`, like this:
```
#if MAC
 namespace fs = std::filesystem;
#else
 namespace fs = std::experimental::filesystem;
#endif
```
everything else compiled as is (for VST2, VST3 had a ton of errors, and AU wouldn't go anywhere due to missing files).

**Comment by asimilon** [comment]
Those changes I detailed above aren't necessary any more (for me at least).  I was building successfully without them (XCode9 and brew llvm) after the #92 merge.

**Comment by esaruoho** [comment]
ok, closing ticket :)
