### ISSUE TITLE
Surge-AU: Building on mac X and running on mac Y does not give access to effect chain or preset changing

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#84]
This one is intriguing.

I built a Surge-AU with one mac#1 (will post specs later), and then zipped it up and transferred it to mac#2 (macOS Mojave 10.14.2 Beta (18C48a)), and for some reason, Logic Pro X did not allow me to change presets or create effect chains.

When time allows today, I'll attempt to re-build with mac#2 and see if I can then change presets and create effect chains. I'll post info about which Xcode version and which macOS version I was running on mac#1 too, but that'll have to wait till monday.

I sure hope @kurasu will merge #69 in soon so it'll be easier to build the AU.

**Comment by baconpaul** [comment]
When you moved it did you move the component and the resources, or just the component?

If you look inside installer-local-AI.sh you see it moves surge.component to ~library/Audio and then does a tar/move/untar of the resources directory to ~library/application support. Both steps are needed to get a working build.

In the other issue, I mentioned building a Mac packager. That may solve all these things or at least regularize them!

**Comment by esaruoho** [comment]
@baconpaul well i must admit, all i did was copy the .component and not the files :)
oops!

mmm.. i guess it's time for a .pkg just like you opened that ticket of yours today..

**Comment by baconpaul** [comment]
Yeah I will get to it tomorrow. Shouldn’t be too hard. Let’s close this issue though since we know what happened now!

**Comment by esaruoho** [comment]
ticket closed.
