### ISSUE TITLE
Surge-VST2: (macOS) Modify premake5.lua to conform to changes in surge-vst2.xcodeproj in asimilon branch

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#86]
Here's a branch by @asimilon https://github.com/asimilon/surge/tree/macOS_VST2_build

This has a modified surge-vst2.xcodeproj - some of these modifications should somehow be emigrated into premake5.lua so that they don't need to be done by hand, instead created when running `build-osx.sh`.
Anyone?

**Comment by asimilon** [comment]
If anyone can point me at some decent documentation or tutorials for premake5 and targeting XCode I could take a stab at it, but I didn't find any useful information anywhere so far.
Also not sure if at all possible, but would be necessary to have 2 options for XCode : 1 for XCode9/brew llvm combo, the other for XCode10.  It would also require some `#ifdef` throughout the code for those 2 targets.

**Comment by esaruoho** [comment]
@asimilon.. what i'm wondering is if i should maybe clone the surge repo as it is, then bake a surge-vst2.xcodeproj and do a Kaleidoscope (app) compare between the files, since they seem to be textfiles. That would at least give me the flags required :)

**Comment by asimilon** [comment]
I have made the correct changes on my fork (pushed to master branch).
AU and VST2 are building correctly and work, VST3 is building and linking, but is not recognised by Reaper, will investigate further.

**Comment by esaruoho** [comment]
for some reason, build-osx.sh will not build a vst2.. 
`target/vst2/Release/surge.dylib` never appears.

so
```
Creating VST Bundle...
cp: target/vst2/Release/Surge.dylib: No such file or directory

** BUILD FAILED **
```

not sure how to encourage the building of vst2 :o
