### ISSUE TITLE
Mac and Linux don't report broken installs to users

### ISSUE THREAD

**Issue by baconpaul** [kurasu/surge#89]
As discussed with @esaruoho and @kzantow both getting it to work without the ~/Library/App Support, the error message for an incomplete install is suppressed on mac and linux.

The code that needs fixing is in SurgeStorage.cpp

```
   string snapshotmenupath = datapath + "configuration.xml";

   if (!snapshotloader.LoadFile(snapshotmenupath.c_str())) // load snapshots (& config-stuff)
   {
#if !MAC && !__linux__
      MessageBox(::GetActiveWindow(), "Surge is not properly installed. Please reinstall.",
                 "Configuration not found", MB_OK | MB_ICONERROR);
#endif
   }
```

**Comment by jsakkine** [comment]
With zero experience on VSTGUI is `CTextEdit` something that can be used for this, or not? Where is the manual for VSTGUI anyway? Just poking its sources randomly.

**Comment by baconpaul** [comment]
Yeah but since this is in a #if MAC anyway I can pop a system alert.

I'll commit this shortly.

<img width="1235" alt="screen shot 2018-12-16 at 10 03 49 am" src="https://user-images.githubusercontent.com/13387561/50055231-ea67eb80-0119-11e9-9474-9279e37a13ea.png">

but I really have a lot of stuff backing up. Any idea when #69 might get merged so I can do the PRs for the other changes I have?

**Comment by baconpaul** [comment]
https://github.com/baconpaul/surge/commit/e5737f0785141147995d57e1d5637a0001c9f183

there's the diff which does that. It's in my zoomable-ui branch which I will send as a PR when #69 is built.

@esaruoho if you end up building a packaged version, perhaps pull head of zoomable-ui so you can get that feedback check?

I'll leave this open until merged. And someone should do the linux equivalent.

**Comment by esaruoho** [comment]
> but I really have a lot of stuff backing up. Any idea when #69 might get merged so I can do the PRs for the other changes I have?

I wish I knew, only @kurasu really knows. 

I would love for #68 #69 and #70 to get merged in asap, that's for sure.

all i can say is, either push the check into #69 as an updats, or hand me the commit and i'll dump it into #68 ..

**Comment by jsakkine** [comment]
Should the error messages be same across plaforms? Just for plain interest, what is the problem with CTextEdit?

**Comment by baconpaul** [comment]
> Should the error messages be same across plaforms? 

Maybe, but the remediations are different, and anyway @kzantow has a fix to get these from resource so it should "never happen"

> Just for plain interest, what is the problem with CTextEdit?

If you google "how to show a modal system alert cocoa stackoverflow" it doesn't give you CTextEdit code to copy and paste. :)  Happy for someone to change it but it seems like a pretty infrequent code path.

**Comment by baconpaul** [comment]
This is now meged
