### ISSUE TITLE
A way to log messages and errors

### ISSUE THREAD

**Issue by baconpaul** [kurasu/surge#94]
So the only way I managed to get the whole thing working was by writing a dumb little class in the audio unit layer called "AULOG" which has one method (::log( char* format, ... )) which fprintfs to stderr and to a log file in the right place on macOS.

My dev cycle looks like "include this where I'm debugging, insert printfs, remove it from where I'm debugging"

So this is fine and all, but wondering what devs on other platforms like linux and windows think about having this be something more central in Surge land. So have src/common/SurgeLog.h and src/common/SurgeLog.cpp which (basically) look like my AULOG for now but is available everywhere and has the right OS-specific things for stuff like where to cache log files and so on. We could also use some external library or do something like proper log date and time formatting in the future if we had such a hook.

I am fine with not doing this. I can just whack away on mac with my little hack in AU only. But since I know some of you (like @jsakkine) are looking at linux and standalone also, I thought having 'one way to do it' would be nice, and also reduces the risk that I accidentally leave an AULOG in non-mac code and what not.

**Comment by asimilon** [comment]
It would be good to wrapper in a macro that is wiped out of existence for Release builds.

**Comment by baconpaul** [comment]
Agreed. My aulog has that mostly (the function becomes a noop which any optimized will optimize away if you set the logger off with an ifdef)

Just we need to pick a name and place and put it there. 

Gotta say I would not have been able to make it work without a reliable printf to log handler though - so I think it is important.

And also, I applaud your optimism in contemplating a Mac or Linux release build! :) I think this will be beta for a while.

**Comment by jsakkine** [comment]
I don't whether it is good or not but many projects favor http://www.pantheios.org/. Worth of looking into anyway just because of the popularity. Here's something about its performance: http://www.pantheios.org/performance.html

**Comment by asimilon** [comment]
Things that 100% need to be avoided on the audio thread:
 - allocations
 - disk i/o

else risk dropouts.  That stuff needs to be done on a separate thread with communication between the two.

**Comment by baconpaul** [comment]
I completely agree with that!

Like I said, my AULOG is a gross hack I used so I wasn't blind (and now I'm in vst I have a not-for-commit similar gross hack). It's really tough and slow to attach a debugger to logic. Much easier to rebuild with a printf, alas. (I have an entire side commentary on the history of debuggers).

Pantheios looks very interesting. Thanks for the link.

**Comment by jsakkine** [comment]
@baconpaul, maybe it is better that you experiment with this? I anyway have my hands full with CMake and you have already sprinkled some logging code that would need to be replaced.

**Comment by baconpaul** [comment]
Yeah I will do so. For now I have it set up so my logging code doesn’t compile in vst3 on purpose so I won’t commit it to the mainline and just have it in startup on au. Will keep it that way until I investigate here.

**Comment by baconpaul** [comment]
From a bit of poking around spdlog (https://github.com/gabime/spdlog) looks like it may be a good choice. Header only. Git repo so it can be done as a Submodule. Cross platform. Async. Scalable. Compile time disable-able. Lots of blog posts saying it is fast.

Anyone here have any validating or contradicting views on that library?

**Comment by asimilon** [comment]
@baconpaul 
> It's really tough and slow to attach a debugger to logic

I use [Hosting AU](http://ju-x.com/hostingau.html) as a lightweight AU host for debugging.

**Comment by baconpaul** [comment]
> I use [Hosting AU](http://ju-x.com/hostingau.html) as a lightweight AU host for debugging.

Wow thanks! I didn't have a middle ground between au lab and logic. That looks great.

**Comment by jsakkine** [comment]
@baconpaul I've heard people using spdlog and not complaining about that too much. It also uses cmake like vst3sdk. I don't exactly know what we gain from this synergy when I convert also Surge to use cmake but that neither can be bad a thing.
@asimilon You can log while playing audio if the logging is implemented right (e.g. copying logs to a buffer and let another thread eventually take care of doing syscalls etc.). Getting some meta-data about buffers being transfered can be very useful sometimes. Of course there needs to be a way to dynamically disable these log messages.

**Comment by jsakkine** [comment]
@baconpaul you can push spdlog whenever you want. Does not effect on what I'm doing.

**Comment by baconpaul** [comment]
Super embarrassingly (for me) @kzantow points out that I can just run Logic Pro from terminal if I want to see the stdout and stderr, so this isn't needed.

It was a super useful thing that let me squash a lot of bugs. Just there's a way better way to do it.

So I'm going to close this and delete the code unmerged.

Sorry for the noise.
